Q1: Write a python program to scrape data for “Data Analyst” Job position in 
“Bangalore” location. You have to scrape the job-title, job-location, company_name,
experience_required. You have to scrape first 10 jobs data.

In [ ]:
! pip install selenium

In [68]:
import selenium
import pandas as pd
from selenium import webdriver

In [ ]:
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [ ]:
url="https://www.naukri.com/data-analyst-jobs-in-bangalore?k=data%20analyst&l=bangalore"
driver.get(url)

Enter “Data Analyst” in “Skill,Designations,Companies” field and enter “Bangalore” in “enter the location” field.

In [ ]:
Search_job = driver.find_element_by_id('qsb-keyword-sugg')
Search_job

In [ ]:
Search_job = driver.find_element_by_xpath('//input[@class="sugInp"]')
Search_job

In [ ]:
Search_job.send_keys("Data Analyst")

In [ ]:
search_loc = driver.find_element_by_id("qsb-location-sugg")
search_loc.send_keys("Bangalore/Bengaluru")

In [ ]:
search_button=driver.find_element_by_xpath("//button[@class='btn-primary']")
search_button.click()

In [ ]:
titles_tags = driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
titles_tags

In [ ]:
job_titles = []
for i in titles_tags:
    job_titles.append(i.text)

job_titles

In [ ]:
company_tags = driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
company_tags

In [ ]:
company_title = []
for i in company_tags:
    company_title.append(i.text)

company_title

In [ ]:
experience_tags = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']")
experience_tags

In [ ]:
experience_list = []
for i in experience_tags:
    experience_list.append(i.text)
experience_list

In [ ]:
job_location = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")
job_location

In [ ]:
location_list = []
for i in job_location:
    location_list.append(i.text)
location_list

In [ ]:
print(len(job_titles), len(company_title), len(experience_list), len(location_list))

In [ ]:
jobs = pd.DataFrame({})
jobs['title'] = job_titles[:10]
jobs['Company'] = company_title[:10]
jobs['Location'] = location_list[:10]
jobs['experience'] = experience_list[:10]

In [ ]:
jobs

Q2: Write a python program to scrape data for “Data Scientist” Job position in 
“Bangalore” location. You have to scrape the job-title, job-location,
company_name, full job-description. You have to scrape first 10 jobs data

In [130]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [131]:
url='https://www.naukri.com/'
driver.get(url)

In [132]:
search_job= driver.find_element_by_id('qsb-keyword-sugg')
search_job.send_keys('Data Scientist')

In [133]:
search_loc=driver.find_element_by_id('qsb-location-sugg')
search_loc.send_keys('Bangalore')

In [134]:
search_button=driver.find_element_by_xpath("//button[@class='btn']")
search_button.click()

In [135]:
title_tag=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title=[]
for i in title_tag:
    title.append(i.text)
title

['Hiring For Data Scientist',
 'Lead Data Scientist BFSI',
 'Associate Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist: Advanced Analytics',
 'Senior Data Scientist',
 'Senior Data Scientist',
 'Sr Data Scientist',
 'Sr Data Scientist',
 'SENIOR DATA SCIENTIST',
 'Senior Data Scientist IN4',
 'Senior Data Scientist (Marketplace)',
 'Hiring For Manager and Sr. Manager | Data Scientist',
 'Requirement For Data Scientist - Mumbai & Bangalore',
 'Data Scientist (Python & SQL)',
 'Lead Data Scientist - Machine Learning/ Data Mining',
 'Data Scientist- Senior Business Analyst/Lead Analyst',
 'Data Scientist- Python/R (3+ Years)',
 'Data Scientist - IN3']

In [142]:
loc=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
location=[]
for i in loc:
    location.append(i.text)
location

['Chennai, Bangalore/Bengaluru, Mumbai (All Areas)',
 '(WFH during Covid)',
 'Bengaluru/Bangalore',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bengaluru/Bangalore',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bengaluru/Bangalore',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Noida, Mumbai, New Delhi, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Bangalore/Bengaluru, Mumbai (All Areas)',
 'Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru']

In [143]:
experience=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']//span")
exp=[]
for i in experience:
    exp.append(i.text)
exp

['3-8 Yrs',
 '5-9 Yrs',
 '3-5 Yrs',
 '4-8 Yrs',
 '4-8 Yrs',
 '3-7 Yrs',
 '6-10 Yrs',
 '7-12 Yrs',
 '6-8 Yrs',
 '6-8 Yrs',
 '5-10 Yrs',
 '7-10 Yrs',
 '4-8 Yrs',
 '8-13 Yrs',
 '2-6 Yrs',
 '6-8 Yrs',
 '6-11 Yrs',
 '2-7 Yrs',
 '3-8 Yrs',
 '3-6 Yrs']

In [144]:
company=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
compname=[]
for i in company:
    compname.append(i.text)
compname

['Tata Consultancy Services Ltd.',
 'IBM India Pvt. Limited',
 'Philips India Limited',
 'Allegis Services India Pvt. Ltd.',
 'Allegis Services India Pvt. Ltd.',
 'IBM India Pvt. Limited',
 'Walmart Labs',
 'Airbnb',
 'IBM India Pvt. Limited',
 'IBM India Pvt. Limited',
 'Happiest Minds Technologies Pvt.Ltd',
 'Walmart Labs',
 'Walmart Labs',
 'Vision Beyond Resources India Private Limited',
 'CRISIL LIMITED',
 'AVE-Promagne',
 'Wrackle Technologies Pvt Ltd',
 'Evalueserve.com Pvt. Ltd',
 'CRESCENDO GLOBAL LEADERSHIP HIRING INDIA PRIVATE L IMITED',
 'Walmart Labs']

In [145]:
job_url=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
url=[]
for i in job_url:
    url.append(i.get_attribute('href'))
url

['https://www.naukri.com/job-listings-hiring-for-data-scientist-tata-consultancy-services-chennai-bangalore-bengaluru-mumbai-all-areas-3-to-8-years-110921000464?src=jobsearchDesk&sid=1631529205623262&xp=1&px=1',
 'https://www.naukri.com/job-listings-lead-data-scientist-bfsi-ibm-india-pvt-limited-bengaluru-bangalore-5-to-9-years-070921901691?src=jobsearchDesk&sid=1631529205623262&xp=2&px=1',
 'https://www.naukri.com/job-listings-associate-data-scientist-philips-india-limited-bangalore-bengaluru-3-to-5-years-060921501985?src=jobsearchDesk&sid=1631529205623262&xp=3&px=1',
 'https://www.naukri.com/job-listings-data-scientist-allegis-services-india-pvt-ltd-bangalore-bengaluru-4-to-8-years-130921603395?src=jobsearchDesk&sid=1631529205623262&xp=4&px=1',
 'https://www.naukri.com/job-listings-data-scientist-allegis-services-india-pvt-ltd-bangalore-bengaluru-4-to-8-years-130921003393?src=jobsearchDesk&sid=1631529205623262&xp=5&px=1',
 'https://www.naukri.com/job-listings-data-scientist-advanced-analytics-ibm-india-pvt-limited-bengaluru-bangalore-3-to-7-years-070921901677?src=jobsearchDesk&sid=1631529205623262&xp=6&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-walmart-labs-bangalore-bengaluru-6-to-10-years-090921501063?src=jobsearchDesk&sid=1631529205623262&xp=7&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-airbnb-bangalore-bengaluru-7-to-12-years-080921500017?src=jobsearchDesk&sid=1631529205623262&xp=8&px=1',
 'https://www.naukri.com/job-listings-sr-data-scientist-ibm-india-pvt-limited-bengaluru-bangalore-6-to-8-years-010921906637?src=jobsearchDesk&sid=1631529205623262&xp=9&px=1',
 'https://www.naukri.com/job-listings-sr-data-scientist-ibm-india-pvt-limited-bangalore-bengaluru-6-to-8-years-010921906105?src=jobsearchDesk&sid=1631529205623262&xp=10&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-happiest-minds-technologies-pvt-ltd-bangalore-bengaluru-5-to-10-years-070921501517?src=jobsearchDesk&sid=1631529205623262&xp=11&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-in4-walmart-labs-bangalore-bengaluru-7-to-10-years-090921501064?src=jobsearchDesk&sid=1631529205623262&xp=12&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-marketplace-walmart-labs-bangalore-bengaluru-4-to-8-years-090921500549?src=jobsearchDesk&sid=1631529205623262&xp=13&px=1',
 'https://www.naukri.com/job-listings-hiring-for-manager-and-sr-manager-data-scientist-vision-beyond-resources-india-private-limited-noida-mumbai-new-delhi-gurgaon-gurugram-bangalore-bengaluru-8-to-13-years-090921005986?src=jobsearchDesk&sid=1631529205623262&xp=14&px=1',
 'https://www.naukri.com/job-listings-requirement-for-data-scientist-mumbai-bangalore-crisil-limited-bangalore-bengaluru-mumbai-all-areas-2-to-6-years-080921005523?src=jobsearchDesk&sid=1631529205623262&xp=15&px=1',
 'https://www.naukri.com/job-listings-data-scientist-python-sql-ave-promagne-hyderabad-secunderabad-chennai-bangalore-bengaluru-6-to-8-years-060921904967?src=jobsearchDesk&sid=1631529205623262&xp=16&px=1',
 'https://www.naukri.com/job-listings-lead-data-scientist-machine-learning-data-mining-wrackle-technologies-pvt-ltd-bangalore-bengaluru-6-to-11-years-080221900886?src=jobsearchDesk&sid=1631529205623262&xp=17&px=1',
 'https://www.naukri.com/job-listings-data-scientist-senior-business-analyst-lead-analyst-evalueserve-com-pvt-ltd-gurgaon-gurugram-bangalore-bengaluru-2-to-7-years-110821005065?src=jobsearchDesk&sid=1631529205623262&xp=18&px=1',
 'https://www.naukri.com/job-listings-data-scientist-python-r-3-years-crescendo-global-leadership-hiring-india-private-l-imited-bangalore-bengaluru-delhi-ncr-mumbai-all-areas-3-to-8-years-110921000469?src=jobsearchDesk&sid=1631529205623262&xp=19&px=1',
 'https://www.naukri.com/job-listings-data-scientist-in3-walmart-labs-bangalore-bengaluru-3-to-6-years-090921500592?src=jobsearchDesk&sid=1631529205623262&xp=20&px=1']

In [146]:
job_desc=[]
for i in url:
    driver.get(i)
    try:
        d=driver.find_elements_by_xpath("//div[@class='dang-inner-html']")
        for i in d:
            job_desc.append(i.text.replace('\n',' '))
    except:
        job_desc.append('-')
job_desc

['Minumum 3 years of experience in Data Science/Machine learning  Location : PAN INDIA Exp : 3 - 7 Years  Minimum 3 year of experience in being Applied Machine Learning Engineer role Research, develop, and implement prediction, optimization, and analytics tools. Document and communicate methodology and results to technical and non-technical audiences Guide and implement best practices of curated data and evaluate ML models on large-scale data Lead design and implementation of Machine Learning algorithms, combining with rule-based optimization to deliver significant improvement in product metrics Write production ready high quality, maintainable and scalable code. Design and analyze metrics to verify model and algorithm effectiveness. Experience with data analysis languages such as Python or Scala Experience with Machine Learning tools (Azure ML, SageMaker, TensorFlow, Kubernetes, etc.) Experience with Machine Learning Languages (R, Python, .Net Core, etc.)',
 'Use predictive modeling to increase and optimize customer experiences, revenue generation, campaign optimization and other business outcomes Work with product management to develop data use cases and embed predictive models in workflows on resource constrained platforms and cloud enabled. Selecting features, building and optimizing classifiers using machine learning and deep learning techniques Collaborates with Data Engineers to enhance data collection and ingestion/curation techniques to include information that is relevant for building analytic systems Processing, cleansing, and verifying the integrity of data used for analysis Develop processes and tools to monitor and analyze model performance and data accuracy. Life cycle management of predictive models. Adherence to compliance procedures in accordance with regulatory standards, requirements, and policies. Managing and designing the reporting environment, including data sources security, and metadata. Job Qualifications: Master s degree or PhD in Computer Science, Information management, Statistics or related field, with 3 to 5 years of experience in the Consumer or Healthcare industry manipulating data sets and building predictive models with focus on product development Experience in statistical modelling, machine learning, data mining, unstructured data analytics and natural language processing. Sound understanding of - Bayesian Modelling, Classification Models, Cluster Analysis, Neural Network, Nonparametric Methods, Multivariate Statistics, etc. Strong hands on knowledge of ML techniques like regression algorithms, K-NN, Na ve Bayes, SVM and ensemble techniques like Random forest, AdaBoost etc Having strong knowledge in unsupervised learning algorithms using Neural networks and Deep-Learning Strong knowledge in Data Wrangling and Exploration techniques to identify the patterns, trends and outliners. Deep knowledge and practical experience with data science toolkits, such as NumPy, Pandas, scikit-learn or equivalent Experience with data visualization tools, such as QlikView, Matplotlib, seaborn or equivalent tools. Proficiency in using query languages, such as SQL, PL/SQL Hands on experience in the one or more databases like Hadoop, AWS Redshift, Snowflake etc. Good applied statistics skills, such as distributions, statistical testing, regression, etc. Good ETL scripting and programming skills, such as Python, R or Scala to integrate developed solution into the proposition. A team player capable of working and integrating across cross-functional team for implementing project requirements. Experience in technical requirements gathering and documentation. Ability to work effectively and independently in a fast-paced global collaborative agile team environment with tight deadlines A flexible, pragmatic and collaborative team player with innate ability to engage with stakeholders at all levels in the organization. A self-starter with high levels of drive, energy, resilience and a desire for professional excellence with a passion for data and data science',
 "Must Have skill sets:  Excellent knowledge of various statistical / Machine Learning / Deep Learning algorithms such as Feature Engineering/selection, Time series, Regression, Classification, Clustering, Recommendation Engine, Anomaly Detection, NLP, Reinforcement Learning etc.) 4 to 8 years of hands-on expertise in developing data science models by applying above mentioned algorithms on structured / text data, using R / Python Proficient in writing optimized query using any one of the DB query language (Hive/Impala/SQL/MongoDB etc.). Knowledge of big data is essential  Good to Have skill sets:  Visualization using any one of the technologies (Tableau, PowerBI, RShiny, matplotlib, ggplot etc.). In case of lack of skills, eagerness to learn is must Insight Generation and Story telling to end consumers Experience across end to end data science project life cycle (use case framing, data collection, data exploration, design of experiments, model development, selection and deployment, post production support) Self-motivated to learn different techniques / technologies, as per the project's need and go extra mile to bring customer delight  Educational Qualification:  Any of the following: • Bachelors in Engineering / MCA • Masters in Data Science/ Computer Applications/ Statistics/ Mathematics/ Economics/ Ops Research/ Other quantitative disciplines • MBA  Job Responsibilities: Own and execute end to end delivery of one or more than one data science model development, as per requirement provided by project/product manager Understand business requirements from Product Managers/Business Users Extract data from multiple data sources using Hadoop / SQL Develop, Validate and Operationalize predictive models using appropriate variables and ML/deep learning techniques Perform ad-hoc deep dive analysis and generate actionable insights Create technical documentation and provide post-production support for a time-bound period Communicate the results to technical as well as business stakeholders across different hierarchies",
 'As a Senior Data Scientist for Walmart, you ll have the opportunity to: Drive data-derived insights across a wide range of divisions by developing advanced statistical models, machine learning algorithms and computational algorithms based on business initiatives Direct the gathering of data, assessing data validity and synthesizing data into large analytics datasets to support project goals Utilize big data analytics and advanced data science techniques to identify trends, patterns, and discrepancies in data. Determine additional data needed to support insights Build and train statistical models and machine learning algorithms Apply your semantic, natural language processing and understanding expertise where required Use deep learning and image recognition project goals Computer Vision will be an important focus area for this role Productionize the models and make those available at scale Build and maintain end to end Machine Learning pipelines Be comfortable with ambiguity and uncertainty and the eagerness to change the world in a huge way by being a self-motivated learner and builder Communicate recommendations to business partners and influencing future plans based on insights Your Responsibility Play a key role to solve complex problems, pivotal to Walmart s business and drive actionable insights from petabytes of data Utilize product mindset to build, scale and deploy holistic data science products after successful prototyping Demonstrate incremental solution approach with agile and flexible ability to overcome practical problems Partner with senior team members to assess customer needs and define business questions Clearly articulate and present recommendations to business partners, and influence future plans based on insights Work with customer centric mindset to deliver high quality business driven analytic solution Drive innovation in approach, method, practices, process, outcome, delivery, or any component of end-to-end problem solving Demonstrates up-to-date expertise and applies this to the development, execution, and improvement of action plans Preferred Qualifications Bachelors degree in Statistics, Mathematics, Computer Science or a related field and 8 years experience in an analytics/DS related field, or, Masters degree in Statistics, Mathematics, Computer Science or a related field and 6 years experience in an analytics/DS related field. High proficiency in data mining, modeling, validation and insight generation. Excellent working knowledge of statistics, mathematics, machine learning, data mining, deep learning High proficiency in coding including Python and SQL Experience with databases (for example, DB2, Oracle, SQL Server) Experience with Big Data technologies such as Pig, Hive and/or Spark Ability to work with large data sets. Has sound understanding of big data technology stack Understanding of cloud computing platforms and large-scale databases Proven ability to collaborate and work in teams Excellent with communications and stakeholder engagement Data science publications in recognized platforms/journals Proven ability to work in agile mode on data science sprint projects',
 'Responsibilities include: Defining and evaluating key metrics and understanding what moves them and why Ownership of conceptualizing, developing, and maintaining dashboards and visualizations Investigating evolving fraud trends to extract patterns, identify root causes and propose actionable solutions Communicating analyses and recommendations to cross functional stakeholders for decision making Empowering the team to answer data questions quickly and easily by building high-quality ground truth data sets Here are example traits we value: Professional industry experience in a quantitative analysis role (7+ years preferred) Comfortable in SQL and some experience with a programming language (Python or R a plus) Ability to communicate clearly and effectively to cross functional partners of varying technical levels Ability to define relevant metrics that can guide and influence stakeholders to the appropriate and accurate insights Experience or willingness to learn tools to create data pipelines using Airflow Building clear and easy to understand dashboards (Tableau) and presentations',
 '  Skills Required Skills: Data Science, Machine Learning, Deep Learning, Python, NLP Desired Skills: Computer Vision Roles and responsibilities Experience in Data Modelling, R, Python, SQL, Data Science, Machine Learning, Deep Learning, NLP, Statistics Have ability to solve Business problems using Data Should possess extensive knowledge of and experience in applying data mining and machine learning techniques on large amount of datasets High level of proficiency in statistical tools like R, Python Candidate will be expected to communicate analytical results in a way that is meaningful for business stakeholders and provides actionable insights. Have the ability to discover new opportunities where advanced analytical techniques can be leveraged for solving business problems Good to Have Expertise in programming languages like Java/C/C /Python Experience with relational databases and SQL is good to have Experience in audio and video analytics Relevant experience in Big Data platforms like Hadoop eco-system Come up with innovative algorithms and solutions Staffing Type:Permanent',
 'Design, coordinate, and implement data driven business and technology solutions to support innovation initiatives Communicate complex models, analysis and recommendations in a clear and precise manner Provide thought leadership in statistical modeling and machine learning/ AI. NLP and Deep Learning are the two focus areas Deliver actionable insights to stakeholders through rich visualization and presentation Manage priorities between research and deliverables effectively Collaborate actively with topic owners to understand and develop advanced analytics / data science Your Qualifications Bachelor s degree in Engineering / Analytics or Master s Degree in Statistics/Computer Applications/ IT/Analytics /any discipline related to Data Science / Analytics. 7 years of progressive experience in Machine learning/Deep learning preferably working with packages like NLTK, BERT, ELMo etc Fluent in Python and have experience with NLP libraries like , Spacy, Genism, Glove, doc2vec etc. Exposure to Microsoft LUIS will be preferred Possess advanced knowledge of the HuggingFace libraries and concepts like tokens, tokenization, stemming, lemmatization, regex. Solid command on statistics and ability to connect theory and practice of data mining, machine learning to solve real-world use case l Strong working knowledge of Python (BERT, GPT, genism, SpaCy, tensorflow, Theano, PyTorch, SciPy, scikit-learn, pandas), SQL, Unix (awk, sed, bash) for data wrangling, data analysis, modeling. Knowledgeable in Natural Language processing (NLP) and quantitative analysis Previous experience building chatbots for Customer Service / specific business verticals (Bonus) Interesting side projects or Kaggle competition results (Bonus) Excellent critical thinking ability, result orientation and project management skills Sound verbal and written communication skills',
 'Position Responsibilities o Solve business problems by applying advanced Machine Learning algorithms and complex statistical models on large volumes of data. o Build, scale and deploy holistic data science products after successful prototyping. o Clearly articulate and present recommendations to business partners, and influence future plans based on insights. o Follow industry best practices, stay up to date with the state of the art in machine learning research and practice, drive innovation by contributing to the latest applied research in data science through publications and patents. o Promote and support company policies, procedures, mission, values, and standards of ethics and integrity. Position Requirements o Deep knowledge of the foundations of machine learning and statistics - can easily understand and implement a machine learning research paper. o Solid experience working with state-of-the-art supervised and unsupervised machine learning algorithms on real-world problems, preferably in ecommerce domain. o Strong Python coding skills and able to work with at least one other programming language such as Java/Scala. o Ability to work in a big data ecosystem - expert in SQL/Hive and ability to work with Spark. o Strong ability to understand the business and good stakeholder management capabilities. Qualifications o PhD with > 2 years of experience / 4-year bachelor s degree with > 7 years of experience / Master s degree with > 5 years of experience. Educational qualifications should be preferably in Computer Science or a related area. Experience should be relevant to the role. Good to have: o Experience in ecommerce domain. o Demonstrated success in data science platforms like Kaggle.',
 'Hello, We are hiring on behalf of one of the largest BPO/ Consulting services. The skills rquired are Natural Language Processing, Python, Data Science and Machine Learning.  Title: Manager / Sr. Manager Location:Bangalore , Gurugram, Mumbai Duration : Fulltime Max Notice:1 Month',
 'CRISIL (formerly Credit Rating Information Services of India Limited) is an Indian analytical company providing ratings, research, and risk and policy advisory services and is a subsidiary of American company S&P Global  We are looking Data Scientist for Mumbai & Bangalore location Candidates who can join immediately or within 30-45 need only apply  Please refer below JD for your reference-  Job Description Data scientist: Client oriented approach to problem solving. Individual should be able to have a holistic view of multiple businesses and develop analytic solutions accordingly. Own and deliver multiple and complex analytic projects. This would require an understanding of business context, conversion of business problems in modeling, and implementing such solutions to create business value. Always up to date with the latest use cases of modeling community, machine learning and deep learning algorithms and share knowledge within the team. Proficiency in basic statistics, hypothesis testing, segmentation and predictive modeling. Ability to translate and articulate technical thoughts and ideas to a larger audience including influencing skills with peers and senior management. Strong project management skills. Ability to coach and mentor juniors. Eagerness to work on new and challenging tasks on a regular basis with an ability to research new ways of doing things better/efficiently. Contribute to organizational initiatives in wide ranging areas including competency development, training, organizational building activities etc. Skills  Basic Qualifications  Bachelors Degree with 2+ years of experience in data analytics, Hands-on experience in Python / SAS or R programing along with strong experience in SQL and Excel Macros. Experienced in working with large and multiple datasets, data warehouses and ability to pull data using relevant programs and coding. Well versed with necessary data preprocessing and feature engineering skills. At least 2 years of experience implementing Machine learning algorithms such as Random Forest and Gradient Boosting in solving business problems such as Default classification and macroeconomic forecasting. At least 1 year of experience implementing deep learning techniques like neural networks Exposure to deep learning packages like Tensorflow Strong background in Statistical Analysis Background in BFSI space will be preferred',
 'Required Technical and Professional Expertise • 6+ years of industry work experience in data scientist projects • Master’s degree or higher in Statistics/Math/Computer Science or related field • Background in applied statistical modeling on large experimental or observational data sets • Experience extracting data from a variety of sources, and a desire to expand those skills (working knowledge SQL is required, Spark is a plus) • Experience with one or more statistical or machine learning software such as R, Python, etc. • Must showcase past work through published articles/GitHub/social media  Preferred Technical and Professional Expertise • Knowledge of distributed computing systems, e.g. Cosmos, Spark, Hadoop, and relational database management system • PhD. in Statistics is preferred • You love collaborative environments that use agile methodologies to encourage creative design thinking and find innovative ways to develop with cutting edge technologies • Ambitious individual who can work under their own direction towards agreed targets/goals and with creative approach to work • Intuitive individual with an ability to manage change and proven time management • Proven interpersonal skills while contributing to team effort by accomplishing related results as needed',
 'Roles and Responsibilities Requirements :  - 6-9 years of strong experience in data mining, machine learning and statistical analysis.  - BS/ MS/ PhD in Computer Science, Statistics, Applied Math, or related areas from Premier institutes ( only IITs / IISc / BITS / Top NITs or top US university should apply)  - Ability to lead and deliver in a fast-paced start-up environment.  - Fluency in tools such as Python/ R/ Matlab etc.  - Strong intuition for data and Keen aptitude on large scale data analysis  - Excellent written and verbal communication skills.  - Ability to collaborate across teams and strong interpersonal skills.',

In [147]:
df=pd.DataFrame()
df['job profile']=title[0:10]
df['Company']=compname[0:10]
df['location']=location[0:10]
df['Experience']=exp[0:10]
df['Description']=job_desc[0:10]
df

,job profile,Company,location,Experience,Description
0,Hiring For Data Scientist,Tata Consultancy Services Ltd.,"Chennai, Bangalore/Bengaluru, Mumbai (All Areas)",3-8 Yrs,Minumum 3 years of experience in Data Science/...
1,Lead Data Scientist BFSI,IBM India Pvt. Limited,(WFH during Covid),5-9 Yrs,Use predictive modeling to increase and optimi...
2,Associate Data Scientist,Philips India Limited,Bengaluru/Bangalore,3-5 Yrs,Must Have skill sets: Excellent knowledge of ...
3,Data Scientist,Allegis Services India Pvt. Ltd.,Bangalore/Bengaluru,4-8 Yrs,"As a Senior Data Scientist for Walmart, you ll..."
4,Data Scientist,Allegis Services India Pvt. Ltd.,Bangalore/Bengaluru,4-8 Yrs,Responsibilities include: Defining and evaluat...
5,Data Scientist: Advanced Analytics,IBM India Pvt. Limited,Bangalore/Bengaluru,3-7 Yrs,"Skills Required Skills: Data Science, Machin..."
6,Senior Data Scientist,Walmart Labs,Bengaluru/Bangalore,6-10 Yrs,"Design, coordinate, and implement data driven ..."
7,Senior Data Scientist,Airbnb,Bangalore/Bengaluru,7-12 Yrs,Position Responsibilities o Solve business pro...
8,Sr Data Scientist,IBM India Pvt. Limited,Bangalore/Bengaluru,6-8 Yrs,"Hello, We are hiring on behalf of one of the l..."
9,Sr Data Scientist,IBM India Pvt. Limited,Bengaluru/Bangalore,6-8 Yrs,CRISIL (formerly Credit Rating Information Ser...

Q3: In this question you have to scrape data using the filters available on the 
webpage as shown below:

In [181]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

In [182]:
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [183]:
url = 'https://www.naukri.com/'
driver.get(url)

In [184]:
job=driver.find_element_by_id('qsb-keyword-sugg')
job.send_keys('Data Scientist')

In [185]:
search=driver.find_element_by_xpath("//button[@class='btn']")
search.click()

In [186]:
delhi=driver.find_element_by_xpath("//span[@title='Delhi / NCR']")
delhi.click()

In [187]:
sal_filter=driver.find_element_by_xpath("//span[@title='3-6 Lakhs']")
sal_filter.click()

In [188]:
title_tag=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title=[]
for i in title_tag:
    title.append(i.text)
title

['Data Scientist / Data Analyst / Business Analytics - MNC Jobs Freshers',
 'Data Scientist/ Machine Learning Engineer',
 'Data Scientist / Data Analyst',
 'Only Fresher / Data Scientist / Data Analyst / Analytics - MNC Jobs',
 'Data Scientist - WFH - MIND Infotech',
 'Data Scientist / Data Analyst / Business Analytics - MNC Jobs Freshers',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist - Insurance',
 'Junior Data Scientists & Engineers',
 'Immediate Openings For Data Scientist For Wipro C2H',
 'Data Scientist',
 'Data Scientist - Machine Learning/ NLP',
 'Data Analyst/Data Scientist',
 'Data Scientist-immediate Joiners',
 'Data Scientist',
 'Data Scientist Internship',
 'Senior Data Scientist',
 'Data Scientist',
 'Senior Data Scientist']

In [189]:
company=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
compname=[]
for i in company:
    compname.append(i.text)
compname

['GABA Consultancy services',
 'Creative Hands HR Consultancy',
 'CARS24',
 'GABA Consultancy services',
 'MOTHERSONSUMI INFOTECH & DESIGNS LIMITED',
 'GABA Consultancy services',
 'R Systems International Ltd.',
 'PROCESS NINE TECHNOLOGIES PVT.LTD.',
 'Huquo Consulting Pvt. Ltd',
 'PY Consultancy',
 'IDESLABS PRIVATE LIMITED',
 'Kusum Healthcare Pvt. Ltd.',
 'TalPro',
 'Skillenable Fintech Private Limited',
 'Quikruit Consulting LLP',
 'Fractal Analytics',
 'iHackers Inc',
 'inVentiv International Pharma Services Pvt. Ltd.',
 'Country Veggie',
 'iNICU']

In [190]:
loca=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
location=[]
for i in loca:
    location.append(i.text)
location

['Ghaziabad, Faridabad, Delhi / NCR',
 'Hyderabad/Secunderabad, Pune, Ahmedabad, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru',
 'Gurgaon/Gurugram',
 'Noida, Gurgaon/Gurugram, Delhi / NCR',
 'Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Noida, New Delhi, Gurgaon/Gurugram',
 'Noida',
 '(WFH during Covid)',
 'Gurgaon/Gurugram',
 '(WFH during Covid)',
 'Noida, Gurgaon/Gurugram',
 'New Delhi, Delhi / NCR',
 'Gurgaon/Gurugram',
 'Delhi / NCR(Okhla)',
 'Gurgaon/Gurugram',
 'Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Noida',
 'Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'New Delhi',
 'Hyderabad/Secunderabad, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Bharuch, Jaipur, Bhopal, Mumbai, Jhansi, Nagpur, Ghaziabad, Jaunpur, Kanpur, Delhi, Lucknow, Agra, Gurgaon, Rajkot, Bengaluru',
 'Delhi']

In [191]:
experience=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']//span")
exp=[]
for i in experience:
    exp.append(i.text)
exp

['0-0 Yrs',
 '0-0 Yrs',
 '1-5 Yrs',
 '0-0 Yrs',
 '3-7 Yrs',
 '0-0 Yrs',
 '3-6 Yrs',
 '1-3 Yrs',
 '2-7 Yrs',
 '0-3 Yrs',
 '5-10 Yrs',
 '4-6 Yrs',
 '2-6 Yrs',
 '2-5 Yrs',
 '2-5 Yrs',
 '3-7 Yrs',
 '0-1 Yrs',
 '3-6 Yrs',
 '1-3 Yrs',
 '1-5 Yrs']

In [192]:
sal=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi salary']//span")
salary=[]
for i in sal:
    salary.append(i.text)
salary

['2,25,000 - 4,75,000 PA.',
 '3,00,000 - 4,00,000 PA.',
 'Not disclosed',
 '2,25,000 - 4,75,000 PA.',
 '4,00,000 - 9,00,000 PA.',
 '2,25,000 - 4,75,000 PA.',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 '2,25,000 - 3,50,000 PA.',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed']

In [193]:
df=pd.DataFrame()
df['Job profile']=title[0:10]
df['company']=compname[0:10]
df['location']=location[0:10]
df['experience']=exp[0:10]
df['salary']=salary[0:10]
df

,Job profile,company,location,experience,salary
0,Data Scientist / Data Analyst / Business Analy...,GABA Consultancy services,"Ghaziabad, Faridabad, Delhi / NCR",0-0 Yrs,"2,25,000 - 4,75,000 PA."
1,Data Scientist/ Machine Learning Engineer,Creative Hands HR Consultancy,"Hyderabad/Secunderabad, Pune, Ahmedabad, Gurga...",0-0 Yrs,"3,00,000 - 4,00,000 PA."
2,Data Scientist / Data Analyst,CARS24,Gurgaon/Gurugram,1-5 Yrs,Not disclosed
3,Only Fresher / Data Scientist / Data Analyst /...,GABA Consultancy services,"Noida, Gurgaon/Gurugram, Delhi / NCR",0-0 Yrs,"2,25,000 - 4,75,000 PA."
4,Data Scientist - WFH - MIND Infotech,MOTHERSONSUMI INFOTECH & DESIGNS LIMITED,"Pune, Chennai, Bangalore/Bengaluru, Delhi / NC...",3-7 Yrs,"4,00,000 - 9,00,000 PA."
5,Data Scientist / Data Analyst / Business Analy...,GABA Consultancy services,"Noida, New Delhi, Gurgaon/Gurugram",0-0 Yrs,"2,25,000 - 4,75,000 PA."
6,Data Scientist,R Systems International Ltd.,Noida,3-6 Yrs,Not disclosed
7,Data Scientist,PROCESS NINE TECHNOLOGIES PVT.LTD.,(WFH during Covid),1-3 Yrs,Not disclosed
8,Data Scientist - Insurance,Huquo Consulting Pvt. Ltd,Gurgaon/Gurugram,2-7 Yrs,Not disclosed
9,Junior Data Scientists & Engineers,PY Consultancy,(WFH during Covid),0-3 Yrs,"2,25,000 - 3,50,000 PA."

Q4: Write a python program to scrape data for first 10 job results for Data scientist 
Designation in Noida location. You have to scrape company_name, No. of days 
ago when job was posted, Rating of the company.

In [194]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [195]:
url='https://www.glassdoor.co.in/index.htm'
driver.get(url)

In [197]:
title_tag=driver.find_element_by_id('sc.keyword')
title_tag.send_keys('Data Scientist')

In [198]:
noida=driver.find_element_by_id('sc.location')
noida.send_keys('Noida')

In [199]:
search=driver.find_element_by_xpath("//span[@class='css-8zxfjs']")
search.click()

In [207]:
title=driver.find_elements_by_xpath("//a[@class='jobLink job-search-key-1rd3saf eigr9kq1']")
comp=[]
for i in title:
    comp.append(i.text)
comp

['Data Scientist',
 'Product: Data Scientist',
 'Data Scientist',
 'Associate Data Scientist',
 'Data Scientist-CAI',
 'Data Scientist Intern',
 'Executive - Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist_HDFC',
 'Data Scientist',
 'Data Scientist: Artificial Intelligence',
 'Data Scientist',
 'Data Analytics Internship',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist (Matlab and Python)',
 'Data Scientist',
 'Data Scientist (Geospatial)',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist (Non-Price Predictive Modeling)',
 'Data Scientist 1',
 'Data Scientist NCT - Associate',
 'Data Scientist',
 'Lead Data Scientist / Artificial Intelligence Scientist',
 'Data Scientist - Climate',
 'Data Scientist']

In [206]:
rating=driver.find_elements_by_xpath("//span[@class=' job-search-key-srfzj0 e1cjmv6j0']")
rate=[]
for i in rating:
    if i.text!='':
        rate.append(i.text)
    else:
        rate.append('-')
rate

['3.9',
 '4.4',
 '4.0',
 '3.6',
 '3.9',
 '3.4',
 '3.7',
 '4.8',
 '3.9',
 '3.6',
 '3.7',
 '4.2',
 '3.9',
 '3.9',
 '3.8',
 '4.1',
 '3.6',
 '3.6',
 '3.6',
 '4.1',
 '3.9',
 '3.6',
 '3.8']

In [208]:
days=driver.find_elements_by_xpath("//div[@class='d-flex align-items-end pl-std css-17n8uzw']")
day=[]
for i in days:
    day.append(i.text)
day

['30d+',
 '30d+',
 '24h',
 '5d',
 '17d',
 '7d',
 '2d',
 '23d',
 '6d',
 '30d+',
 '10d',
 '24h',
 '6d',
 '1d',
 '12d',
 '12d',
 '4d',
 '20d',
 '24d',
 '9d',
 '12d',
 '21d',
 '5d',
 '30d+',
 '23d',
 '30d+',
 '19d',
 '24h',
 '30d+',
 '10d']

In [209]:
df=pd.DataFrame()
df['Company']=comp[0:10]
df['Rating']=rate[0:10]
df['NO. of days ago']=day[0:10]
df

                      Company Rating NO. of days ago
0              Data Scientist    3.9            30d+
1     Product: Data Scientist    4.4            30d+
2              Data Scientist    4.0             24h
3    Associate Data Scientist    3.6              5d
4          Data Scientist-CAI    3.9             17d
5       Data Scientist Intern    3.4              7d
6  Executive - Data Scientist    3.7              2d
7              Data Scientist    4.8             23d
8              Data Scientist    3.9              6d
9         Data Scientist_HDFC    3.6            30d+

Q5: Write a python program to scrape the salary data for Data Scientist designation 
in Noida location.

In [222]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [223]:
url='https://www.glassdoor.co.in/Salaries/index.htm'
driver.get(url)

In [224]:
title_tag=driver.find_element_by_id('KeywordSearch')
title_tag.send_keys('Data Scientist')
loc=driver.find_element_by_id('LocationSearch')
loc.send_keys('Noida')
search=driver.find_element_by_xpath("//button[@class='gd-btn-mkt']")
search.click()

In [232]:
name_tags=driver.find_elements_by_xpath('//div[@class="py css-17435dd"]')
name=[]
for  i in name_tags:
    name.append(i.text)
name

['3.9\n★\nTata Consultancy Services\nData Scientist\n₹6,28,021\n /yr\nRange: ₹4L - ₹13L\n22 salaries\nSee 177 salaries from all locations',
 '3.9\n★\nIBM\nData Scientist\n₹9,08,246\n /yr\nRange: ₹1L - ₹28L\n20 salaries\nSee 155 salaries from all locations',
 '4.1\n★\nAccenture\nData Scientist\n₹11,93,390\n /yr\nRange: ₹6L - ₹23L\n15 salaries\nSee 76 salaries from all locations',
 '3.7\n★\nDelhivery\nData Scientist\n₹12,49,716\n /yr\nRange: ₹5L - ₹1Cr\n15 salaries\nSee 21 salaries from all locations',
 '4\n★\nEricsson-Worldwide\nData Scientist\n₹7,58,335\n /yr\nRange: ₹4L - ₹17L\n14 salaries\nSee 32 salaries from all locations',
 '3.7\n★\nUnitedHealth Group\nData Scientist\n₹12,80,000\n /yr\nRange: ₹8L - ₹16L\n14 salaries\nSee 23 salaries from all locations',
 '3.7\n★\nOptum\nData Scientist\n₹13,55,086\n /yr\nRange: ₹8L - ₹20L\n10 salaries\nSee 29 salaries from all locations',
 '3.9\n★\nOptum Global Solutions\nData Scientist\n₹14,55,430\n /yr\nRange: ₹10L - ₹18L\n10 salaries\nSee 15 salaries from all locations',
 '4.2\n★\nValiance Solutions\nData Scientist\n₹8,86,064\n /yr\nRange: ₹5L - ₹15L\n10 salaries\nSee 12 salaries from all locations',
 '3.6\n★\nEXL Service\nData Scientist\n₹11,10,000\n /yr\nRange: ₹6L - ₹16L\n9 salaries\nSee 13 salaries from all locations',
 '3.8\n★\nCognizant Technology Solutions\nData Scientist\n₹9,62,227\n /yr\nRange: ₹4L - ₹13L\n8 salaries\nSee 83 salaries from all locations',
 '4\n★\nZS Associates\nData Scientist\n₹11,71,868\n /yr\nRange: ₹2L - ₹19L\n8 salaries\nSee 24 salaries from all locations',
 '4\n★\nNagarro\nData Scientist\n₹11,01,815\n /yr\nRange: ₹4L - ₹21L\n8 salaries\nSee 8 salaries from all locations',
 '3.8\n★\nInnovaccer\nData Scientist\n₹12,40,275\n /yr\nRange: ₹6L - ₹17L\n8 salaries\nSee 12 salaries from all locations',
 '3.3\n★\nOYO\nData Scientist\n₹14,51,902\n /yr\nRange: ₹10L - ₹21L\n7 salaries\nSee 15 salaries from all locations',
 '4\n★\ndunnhumby\nData Scientist\n₹11,30,374\n /yr\nRange: ₹8L - ₹21L\n7 salaries\nSee 10 salaries from all locations',
 '3.8\n★\nAmazon\nData Scientist\n₹20,63,782\n /yr\nRange: ₹10L - ₹30L\n6 salaries\nSee 47 salaries from all locations',
 '4.1\n★\nFresher\nData Scientist - Monthly\n₹61,566\n /mo\nRange: ₹25T - ₹1L\n6 salaries\nSee 44 salaries from all locations',
 '4.1\n★\nCARS24.com\nData Scientist\n₹10,80,727\n /yr\nRange: ₹9L - ₹15L\n6 salaries\nSee 6 salaries from all locations',
 '3.8\n★\nVidooly Media Tech\nData Scientist - Monthly\n₹35,040\n /mo\nRange: ₹12T - ₹64T\n6 salaries\nSee 14 salaries from all locations']

In [ ]:
min_tag=driver.find_elements_by_xpath('//div[@class="d-flex mt-xxsm css-79elbk epuxyqn0"]')
minn=[]
maxx=[]
for i in min_tag:
    minn.append(i.text.split()[0])
    maxx.append(i.text.split()[1])

In [ ]:
minn

In [241]:
nosalary_tag=driver.find_elements_by_xpath('//span[@class="m-0 css-1b6bxoo"]')
noofsalary=[]
for  i in nosalary_tag:
    noofsalary.append(i.text)

In [242]:
av_tag=driver.find_elements_by_xpath('//div[@class="col-12 col-lg-4 px-lg-0 d-flex align-items-baseline"]')
avg=[]
for i in av_tag:
    avg.append(i.text.replace('\n',''))

In [243]:
rating_tag=driver.find_elements_by_xpath('//span[@class="m-0 css-kyx745"]')
ratings=[]
for  i in rating_tag:
    ratings.append(i.text)

In [ ]:
df=pd.DataFrame()
df['COMPANY NAME']=name[:10]
df[' Number of salaries']=noofsalary[0:10]
df['Average Salary']=avg[:10]
df['Min Salary']=minn[:10]
df['Max Salary']=maxx[:10]
df['Rating of the company']=ratings[:10]
df

Q6 : Scrape data of first 100 sunglasses listings on flipkart.com. You have to 
scrape four attributes:

In [245]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [246]:
url='https://www.flipkart.com/'
driver.get(url)

In [247]:
title_tag=driver.find_element_by_class_name('_3704LK')
title_tag.send_keys('Sunglasses')

In [248]:
search=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search.click()

In [249]:
brand_tag=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
brand=[]
for i in brand_tag:
    brand.append(i.text)
len(brand)

40

In [250]:
desc_tag=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
desc=[]
for i in desc_tag:
    desc.append(i.text)
len(desc)

40

In [251]:
price_tag=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
price=[]
for i in price_tag:
    price.append(i.text)
price

['₹198',
 '₹295',
 '₹284',
 '₹404',
 '₹237',
 '₹509',
 '₹213',
 '₹499',
 '₹202',
 '₹474',
 '₹331',
 '₹237',
 '₹215',
 '₹520',
 '₹265',
 '₹237',
 '₹399',
 '₹179',
 '₹449',
 '₹299',
 '₹449',
 '₹246',
 '₹859',
 '₹209',
 '₹314',
 '₹266',
 '₹379',
 '₹426',
 '₹215',
 '₹349',
 '₹369',
 '₹199',
 '₹257',
 '₹399',
 '₹239',
 '₹312',
 '₹293',
 '₹399',
 '₹284',
 '₹610']

In [252]:
discount=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']//span")
disc=[]
for i in discount:
    disc.append(i.text)
disc

['88% off',
 '88% off',
 '89% off',
 '79% off',
 '85% off',
 '36% off',
 '80% off',
 '77% off',
 '83% off',
 '68% off',
 '80% off',
 '85% off',
 '78% off',
 '34% off',
 '73% off',
 '85% off',
 '80% off',
 '69% off',
 '79% off',
 '81% off',
 '77% off',
 '83% off',
 '4% off',
 '79% off',
 '75% off',
 '86% off',
 '74% off',
 '83% off',
 '73% off',
 '65% off',
 '58% off',
 '84% off',
 '78% off',
 '84% off',
 '76% off',
 '87% off',
 '82% off',
 '80% off',
 '89% off',
 '23% off']

In [253]:
next=driver.find_element_by_xpath("//a[@class='_1LKTO3']//span")
next.click()

In [254]:
brand_tag2=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")

for i in brand_tag2:
    brand.append(i.text)
len(brand)

80

In [255]:
desc_tag2=driver.find_elements_by_xpath("//a[@class='IRpwTa']")

for i in desc_tag2:
    desc.append(i.text)
desc

['UV Protection, Polarized, Mirrored Rectangular Sunglass...',
 'UV Protection Round Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Gradient Rectangular Sunglasses (Free Si...',
 'UV Protection Aviator Sunglasses (54)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (54)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection Aviator, Wayfarer Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (58)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection, Polarized, Mirrored Rectangular Sunglass...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'Others Round Sunglasses (52)',
 'UV Protection, Riding Glasses Rectangular Sunglasses (F...',
 'Mirrored, UV Protection, Riding Glasses, Others Round S...',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Gradient, Mirrored, Riding Glasses Aviat...',
 'UV Protection, Polarized, Mirrored Retro Square Sunglas...',
 'UV Protection Round Sunglasses (55)',
 'Mirrored Aviator Sunglasses (55)',
 'UV Protection Butterfly Sunglasses (65)',
 'UV Protection, Mirrored, Gradient Round Sunglasses (51)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Rectangular Sunglasses (55)',
 'UV Protection Wayfarer Sunglasses (55)',
 'UV Protection Aviator Sunglasses (58)',
 'Mirrored Aviator Sunglasses (53)',
 'Mirrored Round Sunglasses (53)',
 'Riding Glasses, Others, UV Protection Wrap-around Sungl...',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (55)',
 'UV Protection Aviator Sunglasses (57)',
 'UV Protection Sports Sunglasses (62)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Rectangular, Retro Square...',
 'Night Vision, Riding Glasses Wayfarer Sunglasses (53)',
 'UV Protection, Gradient Aviator Sunglasses (55)',
 'UV Protection, Mirrored Round Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (53)',
 'UV Protection, Night Vision, Riding Glasses Aviator Sun...',
 'UV Protection, Night Vision, Riding Glasses, Gradient, ...',
 'UV Protection, Mirrored Round Sunglasses (54)',
 'Mirrored, UV Protection, Riding Glasses, Others Wrap-ar...',
 'UV Protection, Night Vision, Gradient, Mirrored Round, ...',
 'UV Protection Wayfarer Sunglasses (57)',
 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...',
 'UV Protection, Riding Glasses, Mirrored Wayfarer Sungla...',
 'UV Protection Wayfarer Sunglasses (55)',
 'UV Protection Oval Sunglasses (56)',
 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...',
 'UV Protection Clubmaster Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Rectangular, Retro Square...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'Polarized, UV Protection Retro Square Sunglasses (53)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Others Round Sunglasses (48)',
 'Gradient, UV Protection Round Sunglasses (Free Size)',
 'UV Protection, Gradient Retro Square Sunglasses (Free S...',
 'UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...',
 'UV Protection, Polarized Aviator Sunglasses (32)',
 'Polarized, UV Protection Rectangular Sunglasses (59)',
 'UV Protection Sports Sunglasses (Free Size)',
 'UV Protection, Mirrored Wayfarer Sunglasses (53)',
 'UV Protection Over-sized Sunglasses (60)',
 'UV Protection, Gradient Butterfly, Retro Square Sunglas...']

In [256]:
price_tag2=driver.find_elements_by_xpath("//div[@class='_30jeq3']")

for i in price_tag2:
    price.append(i.text)
price

['₹198',
 '₹295',
 '₹284',
 '₹404',
 '₹237',
 '₹509',
 '₹213',
 '₹499',
 '₹202',
 '₹474',
 '₹331',
 '₹237',
 '₹215',
 '₹520',
 '₹265',
 '₹237',
 '₹399',
 '₹179',
 '₹449',
 '₹299',
 '₹449',
 '₹246',
 '₹859',
 '₹209',
 '₹314',
 '₹266',
 '₹379',
 '₹426',
 '₹215',
 '₹349',
 '₹369',
 '₹199',
 '₹257',
 '₹399',
 '₹239',
 '₹312',
 '₹293',
 '₹399',
 '₹284',
 '₹610',
 '₹284',
 '₹345',
 '₹334',
 '₹398',
 '₹209',
 '₹289',
 '₹260',
 '₹1,239',
 '₹331',
 '₹295',
 '₹295',
 '₹210',
 '₹236',
 '₹331',
 '₹210',
 '₹499',
 '₹236',
 '₹217',
 '₹248',
 '₹284',
 '₹225',
 '₹319',
 '₹299',
 '₹398',
 '₹499',
 '₹269',
 '₹854',
 '₹299',
 '₹449',
 '₹449',
 '₹284',
 '₹331',
 '₹202',
 '₹314',
 '₹208',
 '₹664',
 '₹319',
 '₹221',
 '₹664',
 '₹498']

In [257]:
discount2=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']//span")

for i in discount2:
    disc.append(i.text)
disc

['88% off',
 '88% off',
 '89% off',
 '79% off',
 '85% off',
 '36% off',
 '80% off',
 '77% off',
 '83% off',
 '68% off',
 '80% off',
 '85% off',
 '78% off',
 '34% off',
 '73% off',
 '85% off',
 '80% off',
 '69% off',
 '79% off',
 '81% off',
 '77% off',
 '83% off',
 '4% off',
 '79% off',
 '75% off',
 '86% off',
 '74% off',
 '83% off',
 '73% off',
 '65% off',
 '58% off',
 '84% off',
 '78% off',
 '84% off',
 '76% off',
 '87% off',
 '82% off',
 '80% off',
 '89% off',
 '23% off',
 '85% off',
 '72% off',
 '72% off',
 '73% off',
 '88% off',
 '85% off',
 '84% off',
 '4% off',
 '79% off',
 '87% off',
 '85% off',
 '83% off',
 '80% off',
 '83% off',
 '78% off',
 '37% off',
 '60% off',
 '81% off',
 '80% off',
 '76% off',
 '67% off',
 '84% off',
 '80% off',
 '73% off',
 '61% off',
 '73% off',
 '5% off',
 '62% off',
 '77% off',
 '77% off',
 '71% off',
 '79% off',
 '74% off',
 '75% off',
 '86% off',
 '55% off',
 '83% off',
 '77% off',
 '66% off',
 '67% off']

In [258]:
next=driver.find_element_by_xpath("//a[@class='_1LKTO3']//span")
next.click()

In [259]:
brand_tag3=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")

for i in brand_tag3:
    brand.append(i.text)
brand

['SHAAH COLLECTIONS',
 'Elligator',
 'kingsunglasses',
 'ROZZETTA CRAFT',
 'PIRASO',
 'Fastrack',
 'kingsunglasses',
 'ROZZETTA CRAFT',
 'DEIXELS',
 'ROYAL SON',
 'SHAAH COLLECTIONS',
 'PIRASO',
 'SHAAH COLLECTIONS',
 'Fastrack',
 'SUNBEE',
 'PIRASO',
 'PHENOMENAL',
 'OCCARIO',
 'ROZZETTA CRAFT',
 'New Specs',
 'ROZZETTA CRAFT',
 'Silver Kartz',
 'Fastrack',
 'hipe',
 'SUNBEE',
 'Elligator',
 'ROYAL SON',
 'PIRASO',
 'Rich Club',
 'povty',
 'Fastrack',
 'kingsunglasses',
 'HIPPON',
 'PIRASO',
 'Singco',
 'Elligator',
 'Singco India',
 'PHENOMENAL',
 'kingsunglasses',
 'Fastrack',
 'GANSTA',
 'NuVew',
 'Singco India',
 'Elligator',
 'GANSTA',
 'GANSTA',
 'kingsunglasses',
 'Fastrack',
 'kingsunglasses',
 'PHENOMENAL',
 'GANSTA',
 'hipe',
 'kingsunglasses',
 'Singco India',
 'hipe',
 'Fastrack',
 'DEIXELS',
 'kingsunglasses',
 'ROYAL SON',
 'Silver Kartz',
 'Singco India',
 'PHENOMENAL',
 'Fravy',
 'Elligator',
 'Cruze',
 'Badfella',
 'Fastrack',
 'Rich Club',
 'ROZZETTA CRAFT',
 'ROZZETTA CRAFT',
 'SUNBEE',
 'PIRASO',
 'NuVew',
 'SUNBEE',
 'PIRASO',
 'ROYAL SON',
 'hipe',
 'GANSTA',
 'ROYAL SON',
 'AISLIN',
 'SHAAH COLLECTIONS',
 'Elligator',
 'kingsunglasses',
 'PIRASO',
 'ROZZETTA CRAFT',
 'Fastrack',
 'kingsunglasses',
 'DEIXELS',
 'SHAAH COLLECTIONS',
 'ROZZETTA CRAFT',
 'ROYAL SON',
 'PIRASO',
 'SHAAH COLLECTIONS',
 'Fastrack',
 'SUNBEE',
 'PIRASO',
 'OCCARIO',
 'PHENOMENAL',
 'ROZZETTA CRAFT',
 'New Specs',
 'ROZZETTA CRAFT',
 'Silver Kartz',
 'Fastrack',
 'hipe',
 'ROYAL SON',
 'Rich Club',
 'SUNBEE',
 'Elligator',
 'PIRASO',
 'Fastrack',
 'povty',
 'PIRASO',
 'Singco',
 'Singco India',
 'kingsunglasses',
 'HIPPON',
 'Elligator',
 'PHENOMENAL',
 'Fastrack',
 'kingsunglasses']

In [260]:
len(brand)

120

In [261]:
desc_tag3=driver.find_elements_by_xpath("//a[@class='IRpwTa']")

for i in desc_tag3:
    desc.append(i.text)
desc

['UV Protection, Polarized, Mirrored Rectangular Sunglass...',
 'UV Protection Round Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Gradient Rectangular Sunglasses (Free Si...',
 'UV Protection Aviator Sunglasses (54)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (54)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection Aviator, Wayfarer Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (58)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection, Polarized, Mirrored Rectangular Sunglass...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'Others Round Sunglasses (52)',
 'UV Protection, Riding Glasses Rectangular Sunglasses (F...',
 'Mirrored, UV Protection, Riding Glasses, Others Round S...',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Gradient, Mirrored, Riding Glasses Aviat...',
 'UV Protection, Polarized, Mirrored Retro Square Sunglas...',
 'UV Protection Round Sunglasses (55)',
 'Mirrored Aviator Sunglasses (55)',
 'UV Protection Butterfly Sunglasses (65)',
 'UV Protection, Mirrored, Gradient Round Sunglasses (51)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Rectangular Sunglasses (55)',
 'UV Protection Wayfarer Sunglasses (55)',
 'UV Protection Aviator Sunglasses (58)',
 'Mirrored Aviator Sunglasses (53)',
 'Mirrored Round Sunglasses (53)',
 'Riding Glasses, Others, UV Protection Wrap-around Sungl...',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (55)',
 'UV Protection Aviator Sunglasses (57)',
 'UV Protection Sports Sunglasses (62)',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Rectangular, Retro Square...',
 'Night Vision, Riding Glasses Wayfarer Sunglasses (53)',
 'UV Protection, Gradient Aviator Sunglasses (55)',
 'UV Protection, Mirrored Round Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (53)',
 'UV Protection, Night Vision, Riding Glasses Aviator Sun...',
 'UV Protection, Night Vision, Riding Glasses, Gradient, ...',
 'UV Protection, Mirrored Round Sunglasses (54)',
 'Mirrored, UV Protection, Riding Glasses, Others Wrap-ar...',
 'UV Protection, Night Vision, Gradient, Mirrored Round, ...',
 'UV Protection Wayfarer Sunglasses (57)',
 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...',
 'UV Protection, Riding Glasses, Mirrored Wayfarer Sungla...',
 'UV Protection Wayfarer Sunglasses (55)',
 'UV Protection Oval Sunglasses (56)',
 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...',
 'UV Protection Clubmaster Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Rectangular, Retro Square...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'Polarized, UV Protection Retro Square Sunglasses (53)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Others Round Sunglasses (48)',
 'Gradient, UV Protection Round Sunglasses (Free Size)',
 'UV Protection, Gradient Retro Square Sunglasses (Free S...',
 'UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...',
 'UV Protection, Polarized Aviator Sunglasses (32)',
 'Polarized, UV Protection Rectangular Sunglasses (59)',
 'UV Protection Sports Sunglasses (Free Size)',
 'UV Protection, Mirrored Wayfarer Sunglasses (53)',
 'UV Protection Over-sized Sunglasses (60)',
 'UV Protection, Gradient Butterfly, Retro Square Sunglas...',
 'UV Protection, Polarized, Mirrored Rectangular Sunglass...',
 'UV Protection Round Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection, Gradient Rectangular Sunglasses (Free Si...',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (54)',
 'UV Protection Aviator, Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection Rectangular Sunglasses (58)',
 'UV Protection Aviator Sunglasses (54)',
 'UV Protection, Polarized, Mirrored Rectangular Sunglass...',
 'UV Protection Aviator Sunglasses (Free Size)',
 'UV Protection, Polarized, Mirrored Wayfarer Sunglasses ...',
 'UV Protection Aviator Sunglasses (54)',
 'Others Round Sunglasses (52)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Rectangular Sunglasses (F...',
 'Mirrored, UV Protection, Riding Glasses, Others Round S...',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Gradient, Mirrored, Riding Glasses Aviat...',
 'Mirrored Aviator Sunglasses (55)',
 'UV Protection, Mirrored, Gradient Round Sunglasses (51)',
 'UV Protection, Polarized, Mirrored Retro Square Sunglas...',
 'UV Protection Round Sunglasses (55)',
 'UV Protection Butterfly Sunglasses (65)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (58)',
 'Mirrored Aviator Sunglasses (53)',
 'Riding Glasses, Others, UV Protection Wrap-around Sungl...',
 'UV Protection Rectangular Sunglasses (55)',
 'UV Protection Wayfarer Sunglasses (55)',
 'Mirrored Round Sunglasses (53)',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'UV Protection Wayfarer Sunglasses (55)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)']

In [262]:
price_tag3=driver.find_elements_by_xpath("//div[@class='_30jeq3']")

for i in price_tag3:
    price.append(i.text)
price

['₹198',
 '₹295',
 '₹284',
 '₹404',
 '₹237',
 '₹509',
 '₹213',
 '₹499',
 '₹202',
 '₹474',
 '₹331',
 '₹237',
 '₹215',
 '₹520',
 '₹265',
 '₹237',
 '₹399',
 '₹179',
 '₹449',
 '₹299',
 '₹449',
 '₹246',
 '₹859',
 '₹209',
 '₹314',
 '₹266',
 '₹379',
 '₹426',
 '₹215',
 '₹349',
 '₹369',
 '₹199',
 '₹257',
 '₹399',
 '₹239',
 '₹312',
 '₹293',
 '₹399',
 '₹284',
 '₹610',
 '₹284',
 '₹345',
 '₹334',
 '₹398',
 '₹209',
 '₹289',
 '₹260',
 '₹1,239',
 '₹331',
 '₹295',
 '₹295',
 '₹210',
 '₹236',
 '₹331',
 '₹210',
 '₹499',
 '₹236',
 '₹217',
 '₹248',
 '₹284',
 '₹225',
 '₹319',
 '₹299',
 '₹398',
 '₹499',
 '₹269',
 '₹854',
 '₹299',
 '₹449',
 '₹449',
 '₹284',
 '₹331',
 '₹202',
 '₹314',
 '₹208',
 '₹664',
 '₹319',
 '₹221',
 '₹664',
 '₹498',
 '₹198',
 '₹295',
 '₹284',
 '₹237',
 '₹404',
 '₹509',
 '₹213',
 '₹202',
 '₹331',
 '₹499',
 '₹474',
 '₹237',
 '₹215',
 '₹520',
 '₹265',
 '₹237',
 '₹179',
 '₹399',
 '₹449',
 '₹299',
 '₹449',
 '₹246',
 '₹859',
 '₹209',
 '₹379',
 '₹215',
 '₹314',
 '₹266',
 '₹426',
 '₹369',
 '₹349',
 '₹399',
 '₹239',
 '₹293',
 '₹199',
 '₹257',
 '₹312',
 '₹399',
 '₹610',
 '₹284']

In [263]:
discount3=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']//span")

for i in discount3:
    disc.append(i.text)
len(disc)

120

In [264]:
df=pd.DataFrame()
df['Brand']=brand[0:100]
df['Description']=desc[0:100]
df['Price']=price[0:100]
df['Discount']=disc[0:100]
df

,Brand,Description,Price,Discount
0,SHAAH COLLECTIONS,"UV Protection, Polarized, Mirrored Rectangular...",₹198,88% off
1,Elligator,UV Protection Round Sunglasses (54),₹295,88% off
2,kingsunglasses,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹284,89% off
3,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹404,79% off
4,PIRASO,UV Protection Aviator Sunglasses (54),₹237,85% off
...,...,...,...,...
95,PIRASO,UV Protection Aviator Sunglasses (54),₹237,85% off
96,OCCARIO,Others Round Sunglasses (52),₹179,69% off
97,PHENOMENAL,UV Protection Retro Square Sunglasses (Free Size),₹399,80% off
98,ROZZETTA CRAFT,"UV Protection, Riding Glasses Rectangular Sung...",₹449,79% off
99,New Specs,"Mirrored, UV Protection, Riding Glasses, Other...",₹299,81% off

Q7: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to 
go the link: https://www.flipkart.com/apple-iphone-11-black-64-gb-includesearpods-poweradapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKC
TSVZAXUHGREPBFGI&marketplace.

In [266]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [267]:
url='https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace'
driver.get(url)

In [268]:
click=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
click.click()

In [269]:
page=driver.find_elements_by_xpath("//nav[@class='yFHi8N']//a")
next=[]
for i in page:
    next.append(i.get_attribute('href'))
next

['https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=1',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=2',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=3',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=4',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=5',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=6',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=7',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=8',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=9',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=10',
 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=2']

In [270]:
rate=[]
for i in next:
    driver.get(i)
    rating=driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
    try:
        for j in rating:
            rate.append(j.text)
    except:
        rate.append('-')

In [271]:
rate

['5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '3',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5']

In [272]:
rev=[]
for i in next:
    driver.get(i)
    short=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
    try:
        for j in short:
            rev.append(j.text)
    except:
        rev.append('-')

In [273]:
rev

['Brilliant',
 'Simply awesome',
 'Best in the market!',
 'Perfect product!',
 'Fabulous!',
 'Worth every penny',
 'Great product',
 'Good choice',
 'Worth every penny',
 'Highly recommended',
 'Highly recommended',
 'Perfect product!',
 'Perfect product!',
 'Classy product',
 'Worth every penny',
 'Highly recommended',
 'Perfect product!',
 'Simply awesome',
 'Worth every penny',
 'Terrific',
 'Worth every penny',
 'Wonderful',
 'Nice product',
 'Perfect product!',
 'Classy product',
 'Brilliant',
 'Must buy!',
 'Good choice',
 'Wonderful',
 'Perfect product!',
 'Terrific purchase',
 'Simply awesome',
 'Great product',
 'Mind-blowing purchase',
 'Terrific purchase',
 'Excellent',
 'Simply awesome',
 'Good quality product',
 'Very poor',
 'Classy product',
 'Perfect product!',
 'Must buy!',
 'Fabulous!',
 'Mind-blowing purchase',
 'Mind-blowing purchase',
 'Wonderful',
 'Great product',
 'Very Good',
 'Classy product',
 'Perfect product!',
 'Just wow!',
 'Awesome',
 'Terrific',
 'Pretty good',
 'Terrific purchase',
 'Awesome',
 'Classy product',
 'Brilliant',
 'Terrific',
 'Perfect product!',
 'Awesome',
 'Perfect product!',
 'Very poor',
 'Fabulous!',
 'Excellent',
 'Must buy!',
 'Value-for-money',
 'Best in the market!',
 'Brilliant',
 'Terrific purchase',
 'Good quality product',
 'Best in the market!',
 'Perfect product!',
 'Awesome',
 'Value-for-money',
 'Just wow!',
 'Super!',
 'Classy product',
 'Must buy!',
 'Excellent',
 'Nice product',
 'Mind-blowing purchase',
 'Highly recommended',
 'Terrific',
 'Excellent',
 'Mind-blowing purchase',
 'Pretty good',
 'Wonderful',
 'Wonderful',
 'Worth every penny',
 'Fabulous!',
 'Mind-blowing purchase',
 'Excellent',
 'Super!',
 'Fabulous!',
 'Just wow!',
 'Terrific purchase',
 'Awesome',
 'Decent product',
 'Awesome',
 'Highly recommended',
 'Perfect product!',
 'Perfect product!',
 'Classy product',
 'Worth every penny',
 'Highly recommended',
 'Perfect product!',
 'Simply awesome',
 'Worth every penny',
 'Terrific']

In [274]:
review=[]
for i in next:
    driver.get(i)
    long=driver.find_elements_by_xpath("//div[@class='t-ZTKy']")
    try:
        for j in long:
            review.append(j.text.replace('\n',''))
    except:
        review.append('-')

review

['The Best Phone for the MoneyThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.Compelling ultra-wide cameraNew Night mode is excellentLong battery life',
 'Really satisfied with the Product I received... It’s totally genuine and the packaging was also really good so if ur planning to buy just go for it.',
 'Great iPhone very snappy experience as apple kind. Upgraded from iPhone 7.Pros-Camera top class- Battery top performed-Chipset no need to say as apple kind-Security as you expect from apple- Display super bright industry leading colouraccuracy and super responsive-Build quality as expect from apple sturdypremium durable beautiful stylish.-Os most stable os in smartphone industryCons-No 5G-Display is not based on OLED technology-Charger headphones and 1 apple stic...READ MORE',
 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .',
 'This is my first iOS phone. I am very happy with this product. Very much satisfied with this. I love this phone.',
 'Previously I was using one plus 3t it was a great phoneAnd then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD displayBut I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product redMy experience after using 3 weeks1. The delivery ...READ MORE',
 'Amazing Powerful and Durable Gadget.I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.I’ve attached my puppy pics and no fi...READ MORE',
 'So far it’s been an AMAZING experience coming back to iOS after nearly a decade but it’s not as versatile as android though phone is sturdy dropped it accidentally a couple of times and nothing happened fortunately camera is awesome',
 'i11 is worthy to buy, too much happy with the product. Thank u flipkart I received the item on time..loved it..',
 'iphone 11 is a very good phone to buy only if you can compromise for the display. The display on this is device is pretty good but you can get other options with better displays in this price segment.If you can survive with an HD+ LCD panel with thicker bezels and a notch up top then this is a very good phone for you.Cameras are awesome, battery backup excellent, great performance and a decent premium look. Good job Apple !',
 'What a camera .....just awesome ..you can feel this iPhone just awesome . Good for gaming also ...try pubg in hd it’s just wow',
 'It’s a must buy who is looking for an upgrade from previous generation of iPhones. If you are using XR then still you can hold on for sometime and upgrade to 2020 model else this phone is a must buy . Camera quality is amazing and wide angle is something to count upon. Performance wise it’s amazing and feels premium while holding in hand. So a big YES for this device. Go for 128 GB variant as the 4K videos will occupy lots of space and the storage can get over very quickly. Try to buy it with...READ MORE',
 'Value for money❤️❤️Its awesome mobile phone in the world ...Display was very good and bright ..Trust me freinds you r never regret after Buying..Just go for it....I love this phone and i switch to iphone x to 11',
 'Totally in love with this ❤ the camera quality is amazing just love it 😘😘😘 itsss dammnnnnnn amazing... Must buy iPhone 11 this is my best experience ever ☀👌👌🧡🧡🧡🧡🧡 thanku apple ❤',
 'Best budget Iphone till date ❤️ go for it guys without second thought. Let me explain you guys about Camera, Display, battery, and performance.Camera: at this price range there is no comparison of camera, you’ll love the picture quality as well as video quality. I am a Vlogger I wanted an iPhone with 4k video by front camera and I got this phone and I am more than happy 😃Battery: I use this phone roughly as I am active social media person and I have a youtube channel. so the battery ba...READ MORE',
 "It's my first time to use iOS phone and I am loving my upgradation 😍😍 I love the color, I love the assebility of the phone....I need to learn more about its functionality, but as far as I have seen, it's quite easy and it has a lot of functions to work on, specially if you are a content writer or a blogger you get a lot of content creation platforms and they are really amazing.This phone not only for good quality photography but a lot of other task too.😍💯",
 "Iphone is just awesome.. battery backup is very very nice.. continuously for 10 hours we can use it.camera is just awesome.. display is just fab.i love it alot..i had to wait 15 days for it as i pre ordered it..overalll it's worth the price..these all images are clicked by my iPhone..and i love it.",
 'Excellent camera, good performance, no lag. The lcd display is also good.. but difference come when we watch movie in prime and Netflix, the colours are not vibrant.. as we see in amoled display.. and the charger in box is of 5 watts.. takes more than 3 hours to charge from 0 to 100.. so guys be prepare to buy 18 watts charger . Finally I am an android user, it was my first Iapple phone, I promise u guys the iOS is so smooth.. overall the phone is damn good.... close eyes to buy it.. thanks t...READ MORE',
 'It’s been almost a month since I have been using this phone. I upgraded from an iPhone 8. The main issue with my 8 was battery and this phone is just awesome when it comes to battery. It lasts a day and a half for me with my regular use , internet connected always with 4gCan’t move forward without saying this. Battery of this phone is a life saver when I am traveling or at work when I don’t get the option to chargeCamera is superb. Front cam selfies and back cam photos are just awesome....READ MORE',
 'Really worth of money. i just love it. It is the best phone ever.',
 'Smooth like butter, camera like fantabulous, sound is crystal clear & its red color is damn attractive, i am just loving it. Must buy if you love photography.Lucky to get it in sale, thank you Flipkart.',
 'This is my first ever I phone. Before this I was using my google nexus 5. But moving from android to iOS is a great experience. It’s worth at this price. I will highly recommend it if you want to move to iOS. The best part of this phone is it’s camera and it’s battery life. This two things have won my heart. I loved it. Happy to have it in my hand. Still exploring its features. And can’t forget to mention Flipkart service. Very prompt service and fast delivery.',
 'Awesome Phone. Slightly high price but worth. Better than iPhone XR.Camera is superb and wide angle camera is very clear.12MP selfie camera is also very good.A13 Chip gives a very good and smooth performance.',
 'Battery backup is extraordinary, camera is decent & performance offered by A13 bionic is awsome. The display is good in practical usage like the visibility of display is very good in direct sun light compare to pro models. Iam extremely satisfied for the money I spent.',
 'Superb Product !!!A big and worthy upgrade from mi 3S to iphone 11 .Totally loved it !',
 'I have migrated from OP 7pro... and trust me, iPhone 11 is totally worth it.. following are the reasons:-1)there is ABSOLUTELY NO ISSUE WITH THE DISPLAY... its crisp, sharp and I found it to be much much better than OP7 pro. Netflix, Prime video all run crisply... you won’t miss a thing. True Tone works flawlessly...the display brightness is perfect. OP have not calibrated their screens properly.2) iPhone 11 series have really good cameras... others have spoken in depth about them.3) bat...READ MORE',
 'It’s an amazing product from apple and the camera is simply superb. Phone is faster.Night shot is simply superb and detailing and colour differentiation from camera is an added advantageThis review I have written from iPhone 11 only and I am glad to say outside.Cons wise if we see HD+ display only, no battery percentage indicator as in older iPhone 8.No assistive touch control button in itNo oleophobic coating on back panel glass and finger prints are visible but since I bought mint gr...READ MORE',
 'Looking so good 👍 😍 super 👌 stylish 😎 phoneClean box 📦 good 👍 delivery 👌 fast deliveryOriginal box Original iphone 📱 👌 😍😍😍',
 'I just directly switch from iphone 6s to iphone 11 .The best premium smartphone I recommend to everyone. Excellent quality and colors the iphone have in 11 series.Camera quality is just awesome and the major feel when we hold in our hands. The sound quality and volume is also higher then the previous models.I will recommend to buy iphone 11 instead of pro models , there is nothing much difference as this model contains everything which fulfill our needs.Only one thing that I dislike abo...READ MORE',
 'After 1 month use I found camera quality best compared to my previous Samsung note 10+.Display not good as note 10 also charging too slow.Apple should add fast charger like 11 plus and pro.Best phone for daily use',
 'Upgraded from iphone 6 to 11 best phone for iphone users battery is much better than other iphones camera is awesome love to use it.camera is so clear in night.',
 "It's very high performances devise i am like the service of flipkart delevary very fast and packing very nice perfect phone",
 'Well you all know the specifications . One of a kind. Best iPhone till date. Many enhancements to the camera app with many options. Love the glass body with matte finish in the lens area on the back. Lovely colours to choose from. Best battery in an iPhone till date, enough to last more than a day in normal usage. I tested my iPhone 11 battery and lasted for than 24 hours after full charge still with 30% battery charge left. Watched movies for some time. Normal usage on calls, browsing, musi...READ MORE',
 'This will help you more. See if you are planning to buy iPhone 11. I will say. Yes. But there are some plans I just want to disclose before you buy. 1) If you are an existing iPhone X/XS/XS Max/ XR user, better you guys do not think it to buy. You guys have more or less better gadget. 2) If you are an android user and planning to buy premium phone. I will suggest them to please buy iPhone instead of buying an Android. I bet you will never go back to android after using IOS. Now I want to shar...READ MORE',
 'The built quality is not very premium.The battery back is great .The LCD panel is not so sharp but the brightness level is very High .Camera is super duper awesome.The red colour which people think is bright is actually very soothing and excellent colour to choose from .The A13 Bionic chip is really a flagship processor and can beat any phone which even has 12 gb ram .Camera module is very great and looks very stylish.',
 'Amazing camera and feel super machine I am not describe my feeling but this is amazing Phone I am so lucky I have this',
 'Really good actually this is my first apple product am using its really awesome performance wise excellent. Am really happy with this iphone11',
 'it is very good at performance. Camera is best like before and very smooth response even in water. Don’t buy 12 mini buy iPhone 11 , it is far better than 12 mini believe me ! Have a nice day \uf8ff ☺️',
 'Reviewing again after 5 months. At the beginning the battery and performance was good but it degraded soon. Also I was facing heating issues. The mobile will heat up like a stove sometimes. You cannot even play Pubg even in low settings properly, performance is not a problem but heating is. Also if you play that game for 10 mins the brightness will be automatically down due to over heating even when the auto brightness is set to off. This will not be solved even if u manually increase the bri...READ MORE',
 'We are on apple ecosystem for almost eight years now with couple of iPads and iPhones, including Xr.Bought iPhone 11 as a gift to my daughter who loves it. We chose for a purple coloured one. Believe me it is gorgeous and towards the lighter shade. Dazzling and brilliant!The phone is great and does excellent RAM management like any other Apple device.The screen, though a LCD and lesser ppi as compared to other flagship phones of competitor brands, is a delight to watch with perfect re...READ MORE',
 'It is just awesome mobile for this price from Apple,After 10 days reviewBattery enough for 1 day even 24*7 Internet will be on and mostly internet usageCamera is just awesome cool , android 64 MP is equal to this just 12 MPA13 Bionic chip will give more high performance without hangingAudio stereo speakers will give Dolby atoms sound with crystal clearVideo recording is like cinematic shots of every sec can be a 4K 60fps. Just awesome this phoneiPhone 11 loved one',
 'Best Apple iPhone that i have bought at a very reasonable price, camera quality is next level just awesome n of superior quality android phones not even close(RIP) to that and also battery is really good but packaging by Flipkart of iPhone was very poor of such a expensive product, firstly im bit worried about the quality of product if i purchased it through online how was the product but i think now this was mine best decision to bought it through Flipkart online because i got genuine Apple...READ MORE',
 "I can say I'm damn impressed with iPhone 11. As they says iPhone 11 have the toughest glass ever in the smartphone which you'll find on the front and back and it's totally smooth. The fit and finish is full apple quality - there's no sense that any cheaping out has happened in the construction. Without saying it's camera features this review won't complete. The iPhone 11 has a dual camera system, consisting of a wide angle len's that's pretty much same as found on the iPhone XR last year, but...READ MORE",
 'Best Quality Product OF iPhone Series , Sound Quality & Camera quality is very awesome, Battery Life is very Sufficient for 24 hr Backup With Full Internet Access , I love this this Product too much , It is very fast & making me Very fast in all my daily RoutineHighlights;1.Camera: 5 STAR2.Video Recording: 5 star3.Night mODE sHOOTING & Camera:4 star4. Audio Quality: Awesome5. Battery : 5 Star6. Touch:5 Star7. Processor: Very FastThe M...READ MORE',
 'First thanks to Flipkart for this amazing deal and phone is outstanding. I upgraded from iPhone 7 and this is like very big upgrade. But the packaging was very basic I expected a good packaging as they only wrapped one layer of bubble wrap which I don’t think is enough to protect this expensive phone. And I recommend this phone and seller as well.And I’m posting this review after using it for 4 days.',
 'Superfast delivery by Flipkart. Thanks.1. iPhone 11 is a pretty solid phone for the money you are paying.2. All the bad reviews about the display is confusing. It’s not that bad.3. I switched from a Oneplus 7t. I have no complaints about the display quality of iPhone. Yes, it’s not OLED, so, we are missing on the deep blacks. But that’s it. It is a very colour accurate display. Gets adequately bright and I could not find any pixelation.4. Performance is one of the best, if not best, in ...READ MORE',
 "Again back to apple iphone after a gap of 2-3 years. It's pleasure to use iOS and the quality product by Apple. Iphone 11 still works like a beast in 2021 also. It really capable of doing day to day usage as well as hard core gaming. Battery is awesome. I'm really too much satisfied with it. Apart fto the very gorgious IPS LCD (AMOLED will be better) everything is mind boggling. Iphone💕.",
 'impressive super phone and best in class camera ,sound and face unlock is super fast just see and phone is unlock and fast in daily apps use',
 'Well while switching from android to iOS the first thing you need to be careful about is that you will loose all your whatsapp chat backups as both are different operating systems. Camera clarity is awesome and though being an lcd screen clarity and resolution is good. Battery backup is also good unlike previous gen iPhone. So far the experience is good will Padre after a few months of usage.P.S the black is more of a dark grey shade and not jet black',
 'In love with this iphone great performance,camera ,battery everything. Go for it have a uncompareble battery backup, no doubts in iPhone camera here You can see the picture which is shot on my iPhone In love with this iphone great performance,camera ,battery everything. Go for it have a uncompareble battery backup, no doubts in iPhone camera here You can see the picture which is shot on my iPhone In love with this iphone great performance,camera ,battery everything. Go for it have a uncompare...READ MORE',
 'Best in class. Battery backup is good especially when you play games like Pubg COD. But it is sort of heavy when you hold in hands. Portrait mode is best to click pictures. Stage light effect is awesome. Try to click photos outside in nature because photos inside home or room will not give you the quality in any phone even in DSLR.',
 'Very excited to have this phone. This phone has the real power unlike the android phones having SD 855 . The battery life is very good and the camera quality is excellent as comapred to redmi and other phones except google pixel. I M enjoying every single bit of it. Would recommed only if you have the budget.',
 "I upgraded (downgraded?) from my iPhone X since the phone fell down and I didn't want to repair the screen. The box that the phone came in was super slim and I was worried that there'd be no 5W charger with it and my fears were confirmed. However, thankfully I had the 18W USB-C PD charger from Apple which I bought for my iPhone X and it worked perfectly. The charging time is as lethargic as ever though and it takes about 1:30 mins or even 2 hours depending on charge remaining. I'll list some ...READ MORE",
 'I was using Iphone 6s and also Oneplus 6t. Both mobiles were perfectly alright in Photos, gaming, and smooth interface . My 6s mobile getting battery issue. thought upgrade to 11. Really like this mobile of its Internal storage (compare to 6s) , camera and its touch feeling. Its a worth buying mobile for me.',
 'Its Very awesome product working and good camera quality and all about best product and also flipkart is very great deal and offer nice price',
 'I am using this phone for 5 days and its one of the best camera out there ❤️ the screen is not oled and i am coming from iphone xs so its little bit not up to the mark i would sayBut overall value for money💕😍the battery back up is far better than my iphone xs and its worth in my apple ecosystem💫❤️if u are an apple User and have the eco system then go for it❤️though i will be getting the new iphone but its pretty good💫',
 'Best and amazing product.....phone looks so premium.... battary is also good as expected .... Wide angle camera is so addictive ...if you are a IOS lover....then this phone will be the best choice for you all!!💯🔥',
 'Excellent camera and display touching very nice and smooth very improvement against iPhone XR and new processor is very fast',
 "I got this beast today. And I must say the picture quality of its camera is awesome. Both the cameras works fine.As for as the processing is concerned, it runs without any lag. You can play and do whatever you want without a glitch.The battery runs for a day with medium and high workload.The display is good and the speakers are working fine.The earphones doesn't have any base and you can use it for calling mostly.The charging time is approximately for 90 minutes for full charging...READ MORE",

In [275]:
df=pd.DataFrame()
df['Rating']=rate[0:100]
df['review_summary']=rev[0:100]
df['full review']=review[0:100]
df

,Rating,review_summary,full review
0,5,Brilliant,The Best Phone for the MoneyThe iPhone 11 offe...
1,5,Simply awesome,Really satisfied with the Product I received.....
2,5,Best in the market!,Great iPhone very snappy experience as apple k...
3,5,Perfect product!,Amazing phone with great cameras and better ba...
4,5,Fabulous!,This is my first iOS phone. I am very happy wi...
...,...,...,...
95,5,Just wow!,The ultimate performanceCamera is superbThe ba...
96,3,Terrific purchase,I use a Note10+ and have been using both iOS a...
97,5,Awesome,The phone is completely goodAs far as camera A...
98,5,Decent product,Everything u ll like it when u use this iPhone...
99,5,Awesome,Can’t beat the software and hardware integrati...

Q8: Scrape data for first 100 sneakers you find when you visit flipkart.com and 
search for “sneakers” in the search field.

In [276]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [277]:
url='https://www.flipkart.com/'
driver.get(url)

In [278]:
search=driver.find_element_by_xpath("//input[@class='_3704LK']")
search.send_keys('Sneakers')

In [280]:
button=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
button.click()

In [281]:
page=driver.find_elements_by_xpath("//nav[@class='yFHi8N']//a")
next=[]
for i in page:
    next.append(i.get_attribute('href'))
next=next[0:3]
next

['https://www.flipkart.com/search?q=Sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1',
 'https://www.flipkart.com/search?q=Sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2',
 'https://www.flipkart.com/search?q=Sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3']

In [ ]:
money=driver.find_elements_by_xpath("//a[@class='_3bPFwb']//div[@class='_30jeq3']")

price=[]
for i in discount:
    price.append(i.text)
len(price)

In [292]:
discount=driver.find_elements_by_xpath("//a[@class='_3bPFwb']//span")

In [289]:
brands=[]

for i in next:
    driver.get(i)
    title=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    try:
        for j in title:
            brands.append(j.text)
    except:
        brands.append('-')
        
brands

['bluemaker',
 'bluemaker',
 'Magnolia',
 'BRUTON',
 'Chevit',
 'Longwalk',
 'ASTEROID',
 'Nilatin',
 'luxury fashion',
 'PEHANOSA',
 'BIRDE',
 'BAUCHHAAR',
 'Creer',
 'Numenzo',
 'Numenzo',
 'Echor',
 'Shoes Bank',
 'RODDICK SHOES',
 'World Wear Footwear',
 'Peelu',
 'Kraasa',
 'Absolute comfort',
 'believe',
 'bluemaker',
 'ASTEROID',
 'SCATCHITE',
 'Airland',
 'Absolutee shoes',
 'Numenzo',
 'Arohi',
 'Numenzo',
 'India hub',
 'restinfoot',
 'HOC',
 'Robbie jones',
 'pollachief',
 'VIPSJAZZY',
 'RODDICK SHOES',
 'SHOEFLY',
 'BRUTON',
 'BIRDE',
 'BRUTON',
 'bluemaker',
 'bluemaker',
 'SPARX',
 'BRUTON',
 'Jack Diamond',
 'bluemaker',
 'Jack Diamond',
 'Zsyto',
 'Zorth',
 'Nilatin',
 'BIRDE',
 'Chevit',
 'SPARX',
 'BAUCHHAAR',
 'SPARX',
 'Labbin',
 'TR',
 'Echor',
 'Robbie jones',
 'Robbie jones',
 'Magnolia',
 'Peelu',
 'PUMA',
 'Zorth',
 'SHOEFLY',
 'bluemaker',
 'Kraasa',
 'SPARX',
 'BIRDE',
 'Chevit',
 'SPARX',
 'Rising Wolf',
 'bluemaker',
 'STRANGER BROTHERS',
 'T-ROCK',
 'KANEGGYE',
 'WRIZT',
 'Baogi',
 'PUMA',
 'India hub',
 'SPARX',
 'bluemaker',
 'D-SNEAKERZ',
 'Robbie jones',
 'HOC',
 'bluemaker',
 'SPARX',
 'Zsyto',
 'Jokatoo',
 'Nilatin',
 'BIRDE',
 'LuvShus',
 'India hub',
 'BAUCHHAAR',
 'BIRDE',
 'SPARX',
 'Englewood',
 'Echor',
 'HOTSTYLE',
 'Zsyto',
 'PUMA',
 'Peelu',
 'WRIZT',
 'Carlo Style',
 'BRUTON',
 'bluemaker',
 'Ardeo',
 'Numenzo',
 'World Wear Footwear',
 'Chevit',
 'Zorth',
 'PUMA',
 'ADIDAS',
 'Absolutee shoes',
 'D-SNEAKERZ',
 'RODDICK SHOES',
 'World Wear Footwear',
 'Baogi']

In [293]:
desc=[]
for i in next:
    driver.get(i)
    descript=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
    try:
        for j in descript:
            desc.append(j.text)
    except:
        desc.append('-')

In [294]:
desc

['casual for men (blue 08) Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For ...',
 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...',
 'Men Boxer Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Black Sneaker For Men Sneakers For Men',
 'New Collection Pair of Stylish Shoe Sneakers For Men',
 'Sneakers For Men',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'White Sneaker For Men Sneakers For Men',
 'HAWK21 Sneakers For Men',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'Series 7 Sneakers For Men',
 'Sneakers for men(black_6) Sneakers For Men',
 'casual for men Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Sneakers Sneakers For Men',
 'shoe Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Casual Sneaker for Men Sneakers For Men',
 "Casual shoes,Sneakers for men's,shoes for men's Sneaker...",
 'Luxury Fashionable Breathable Casual Sneakers Shoes For...',
 'Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 'ABSOLUTEE SHOES ORANGE GYM SHOE FOR MEN Sneakers For Me...',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Modern & Trendy Collection Combo Pack of 02 Shoes for M...',
 'casual for men (beige 06) Sneakers For Men',
 'casual for men (blue 08) Sneakers For Men',
 'Men White Sneakers Sneakers For Men',
 'Sneakers For Men',
 'New Fashion Outdoor Trendy Lightweight Casual,Canvas St...',
 'Black Sneaker For Men Sneakers For Men',
 "Men's Stylish Casual Shoes Sneakers For Men",
 'Smart Casuals Canvas Shoes Combo pack of 2 Sneakers For...',
 'SM-675 Sneakers For Men',
 'Sneakers For Men',
 'SM-482 Sneakers For Men',
 'Casual Sneakers White Shoes For Men And Boys Sneakers F...',
 'Sneakers For Men',
 'HAWK21 Sneakers For Men',
 'Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men',
 'White Sneakers Sneakers For Men',
 'Puma Kor IDP Sneakers For Men',
 'Sneakers For Men',
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 'casual for men Sneakers For Men',
 'Shark-41 Sneakers For Men',
 'SM-162 Sneakers For Men',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'ABSOLUTEE SHOES ORANGE GYM SHOE FOR MEN Sneakers For Me...',
 'SD-323 Sneakers For Men',
 'Sneakers For Men',
 'casual shoe for men Sneakers For Men',
 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 'Sneakers For Men',
 'Sneakers For Men',
 'X-Ray 2 Square Mid WTR Sneakers For Men',
 'casual for men (blue 08) Sneakers For Men',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'Casual Sneakers Shoes For Men And Boys Sneakers For Men',
 'Luxury Fashionable Breathable Casual Sneakers Shoes For...',
 'Sneakers For Men',
 'SM-322 Sneakers For Men',
 'Black Sneaker For Men Sneakers For Men',
 'Combo Pack of 2 Casual Shoes Sneakers For Men',
 'Men Casual Shoe New Trend With Fashion Panda Desgined L...',
 'Sneakers For Men',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Casual Sneakers Sneakers For Men',
 'White Sneakers | Top Rated Shoes | Gym Shoes | Running ...',
 'HAWK21 Sneakers For Men',
 '3 Pair Combo Sneakers For Men',
 'X-Ray Sneakers For Men',
 'Mens Canvas Shoes for boys (Black) Sneakers For Men',
 'casual for men Sneakers For Men',
 'RAMBOW FUNKY SHOE FOR GYM OUTDOOR WALKING Sneakers For ...',
 'Sneakers For Men',
 '303 Sneakers For Men',
 'ABSOLUTEE SHOES ORANGE GYM SHOE FOR MEN Sneakers For Me...',
 'Lazy Knit Slip On IDP Sneakers For Men',
 'ADISET 1.0 M Sneakers For Men',
 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Re...",
 'Men & Boys Stylish, Comfortable Mesh Shoes With Soft La...',
 'Sneakers For Men',
 'Sneakers For Men']

In [295]:
discount=driver.find_elements_by_xpath("//a[@class='_3bPFwb']//span")

In [296]:
brands=[]

for i in next:
    driver.get(i)
    title=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    try:
        for j in title:
            brands.append(j.text)
    except:
        brands.append('-')

In [297]:
brands

['bluemaker',
 'bluemaker',
 'Magnolia',
 'BRUTON',
 'Chevit',
 'Longwalk',
 'ASTEROID',
 'Nilatin',
 'luxury fashion',
 'PEHANOSA',
 'BIRDE',
 'BAUCHHAAR',
 'Creer',
 'Numenzo',
 'Numenzo',
 'Echor',
 'Shoes Bank',
 'RODDICK SHOES',
 'World Wear Footwear',
 'Peelu',
 'Kraasa',
 'Absolute comfort',
 'believe',
 'bluemaker',
 'ASTEROID',
 'SCATCHITE',
 'Airland',
 'Absolutee shoes',
 'Numenzo',
 'Arohi',
 'Numenzo',
 'STRANGER BROTHERS',
 'restinfoot',
 'HOC',
 'Robbie jones',
 'India hub',
 'VIPSJAZZY',
 'RODDICK SHOES',
 'SHOEFLY',
 'pollachief',
 'BIRDE',
 'BRUTON',
 'bluemaker',
 'bluemaker',
 'SPARX',
 'BRUTON',
 'Jack Diamond',
 'bluemaker',
 'Jack Diamond',
 'Zsyto',
 'Zorth',
 'Nilatin',
 'BIRDE',
 'Chevit',
 'SPARX',
 'BAUCHHAAR',
 'SPARX',
 'Labbin',
 'TR',
 'Echor',
 'Robbie jones',
 'Robbie jones',
 'Magnolia',
 'Peelu',
 'PUMA',
 'Zorth',
 'SHOEFLY',
 'bluemaker',
 'Kraasa',
 'SPARX',
 'BIRDE',
 'Chevit',
 'SPARX',
 'Rising Wolf',
 'bluemaker',
 'Absolutee shoes',
 'T-ROCK',
 'KANEGGYE',
 'WRIZT',
 'Baogi',
 'Extoes',
 'D-SNEAKERZ',
 'PUMA',
 'bluemaker',
 'SPARX',
 'Robbie jones',
 'World Wear Footwear',
 'bluemaker',
 'Jokatoo',
 'Zsyto',
 'BIRDE',
 'Nilatin',
 'India hub',
 'BRUTON',
 'LuvShus',
 'BAUCHHAAR',
 'SPARX',
 'India hub',
 'BIRDE',
 'Echor',
 'Englewood',
 'HOC',
 'HOTSTYLE',
 'Peelu',
 'Zsyto',
 'PUMA',
 'WRIZT',
 'bluemaker',
 'Carlo Style',
 'RODDICK SHOES',
 'Ardeo',
 'Absolutee shoes',
 'Numenzo',
 'D-SNEAKERZ',
 'ADIDAS',
 'STRANGER BROTHERS',
 'Zorth',
 'PUMA',
 'World Wear Footwear',
 'Chevit']

In [298]:
desc=[]
for i in next:
    driver.get(i)
    descript=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
    try:
        for j in descript:
            desc.append(j.text)
    except:
        desc.append('-')

In [299]:
desc

['casual for men (blue 08) Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For ...',
 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...',
 'Men Boxer Sneakers For Men',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Black Sneaker For Men Sneakers For Men',
 'New Collection Pair of Stylish Shoe Sneakers For Men',
 'Sneakers For Men',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'White Sneaker For Men Sneakers For Men',
 'HAWK21 Sneakers For Men',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'Sneakers for men(black_6) Sneakers For Men',
 'casual for men Sneakers For Men',
 'Series 7 Sneakers For Men',
 'shoe Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 "Casual shoes,Sneakers for men's,shoes for men's Sneaker...",
 'Luxury Fashionable Breathable Casual Sneakers Shoes For...',
 'Casual Sneaker for Men Sneakers For Men',
 'Sneakers For Men',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...',
 'casual for men (blue 10) Sneakers For Men',
 'Combo Pack Of 3 Latest Casual Shoes Sneakers For Men',
 'Modern & Trendy Collection Combo Pack of 02 Shoes for M...',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Men White Sneakers Sneakers For Men',
 'casual for men (blue 08) Sneakers For Men',
 'casual for men (beige 06) Sneakers For Men',
 'New Fashion Outdoor Trendy Lightweight Casual,Canvas St...',
 'Sneakers For Men',
 "Men's Stylish Casual Shoes Sneakers For Men",
 'Black Sneaker For Men Sneakers For Men',
 'Smart Casuals Canvas Shoes Combo pack of 2 Sneakers For...',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'Sneakers For Men',
 'SM-482 Sneakers For Men',
 'Casual Sneakers White Shoes For Men And Boys Sneakers F...',
 'SM-675 Sneakers For Men',
 'HAWK21 Sneakers For Men',
 'Casual Sneakers Shoes For Men Sneakers For Men',
 'White Sneakers Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Combo Men Pack of 2 Loafers Shoes Sneakers For Men',
 'Puma Kor IDP Sneakers For Men',
 'casual for men Sneakers For Men',
 'SM-162 Sneakers For Men',
 'Sneakers For Men',
 'Shark-41 Sneakers For Men',
 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...',
 'SD-323 Sneakers For Men',
 'Sneakers For Men',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 'Sneakers For Men',
 'casual shoe for men Sneakers For Men',
 'Sneakers For Men',
 'Casual Sneaker for Men Sneakers For Men',
 'Modern Trendy Shoes Combo pack of 4 Sneakers For Men',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'X-Ray 2 Square Mid WTR Sneakers For Men',
 'casual for men (blue 08) Sneakers For Men',
 'SM-322 Sneakers For Men',
 'Casual Sneakers Shoes For Men And Boys Sneakers For Men',
 '303 Sneakers For Men',
 'Sneakers For Men',
 'Combo Pack of 2 Casual Shoes Sneakers For Men',
 'Black Sneaker For Men Sneakers For Men',
 'Men Casual Shoe New Trend With Fashion Panda Desgined L...',
 'Sneakers For Men',
 'Casual Sneakers Sneakers For Men',
 'Birde Trendy Casual Shoes Sneakers For Men',
 'HAWK21 Sneakers For Men',
 'White Sneakers | Top Rated Shoes | Gym Shoes | Running ...',
 'Luxury Fashionable Breathable Casual Sneakers Shoes For...',
 '3 Pair Combo Sneakers For Men',
 'X-Ray Sneakers For Men',
 'casual for men Sneakers For Men',
 'Mens Canvas Shoes for boys (Black) Sneakers For Men',
 'Men & Boys Stylish, Comfortable Mesh Shoes With Soft La...',
 'RAMBOW FUNKY SHOE FOR GYM OUTDOOR WALKING Sneakers For ...',
 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...',
 'Sneakers For Men',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Re...",
 'ADISET 1.0 M Sneakers For Men',
 'Lazy Knit Slip On IDP Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men']

In [300]:
price=[]

for i in next:
    driver.get(i)
    money=driver.find_elements_by_xpath("//a[@class='_3bPFwb']//div[@class='_30jeq3']")
    
    try:
        for j in money:
            price.append(j.text)
            
    except:
        price.append('-')
price

['₹449',
 '₹449',
 '₹356',
 '₹474',
 '₹599',
 '₹236',
 '₹499',
 '₹449',
 '₹449',
 '₹375',
 '₹359',
 '₹448',
 '₹398',
 '₹429',
 '₹449',
 '₹454',
 '₹349',
 '₹474',
 '₹499',
 '₹442',
 '₹240',
 '₹198',
 '₹449',
 '₹449',
 '₹444',
 '₹264',
 '₹398',
 '₹399',
 '₹449',
 '₹398',
 '₹460',
 '₹468',
 '₹349',
 '₹378',
 '₹379',
 '₹629',
 '₹499',
 '₹474',
 '₹449',
 '₹526',
 '₹444',
 '₹283',
 '₹623',
 '₹449',
 '₹449',
 '₹168',
 '₹435',
 '₹449',
 '₹398',
 '₹283',
 '₹627',
 '₹449',
 '₹630',
 '₹399',
 '₹283',
 '₹448',
 '₹985',
 '₹399',
 '₹745',
 '₹454',
 '₹399',
 '₹311',
 '₹499',
 '₹442',
 '₹499',
 '₹362',
 '₹1,400',
 '₹449',
 '₹849',
 '₹439',
 '₹444',
 '₹599',
 '₹625',
 '₹569',
 '₹379',
 '₹449',
 '₹449',
 '₹399',
 '₹445',
 '₹378',
 '₹789',
 '₹384',
 '₹3,690',
 '₹449',
 '₹719',
 '₹474',
 '₹299',
 '₹449',
 '₹445',
 '₹398',
 '₹472',
 '₹449',
 '₹449',
 '₹215',
 '₹449',
 '₹448',
 '₹935',
 '₹399',
 '₹359',
 '₹454',
 '₹475',
 '₹398',
 '₹611',
 '₹442',
 '₹398',
 '₹3,500',
 '₹299',
 '₹449',
 '₹380',
 '₹474',
 '₹449',
 '₹449',
 '₹449',
 '₹346',
 '₹1,943',
 '₹599',
 '₹439',
 '₹1,047',
 '₹240',
 '₹629']

In [301]:
disc=[]
for i in next:
    driver.get(i)
    discount=driver.find_elements_by_xpath("//a[@class='_3bPFwb']//span")
    try:
        for j in discount:
            disc.append(j.text)
    except:
        disc.append('-')

In [302]:
disc

['55% off',
 '55% off',
 '64% off',
 '86% off',
 '66% off',
 '52% off',
 '75% off',
 '65% off',
 '65% off',
 '62% off',
 '28% off',
 '55% off',
 '60% off',
 '66% off',
 '65% off',
 '54% off',
 '65% off',
 '52% off',
 '50% off',
 '55% off',
 '51% off',
 '60% off',
 '55% off',
 '55% off',
 '55% off',
 '47% off',
 '60% off',
 '55% off',
 '77% off',
 '60% off',
 '53% off',
 '80% off',
 '65% off',
 '81% off',
 '62% off',
 '53% off',
 '50% off',
 '52% off',
 '55% off',
 '82% off',
 '82% off',
 '43% off',
 '16% off',
 '55% off',
 '55% off',
 '71% off',
 '56% off',
 '55% off',
 '69% off',
 '43% off',
 '37% off',
 '65% off',
 '36% off',
 '60% off',
 '43% off',
 '55% off',
 '26% off',
 '60% off',
 '6% off',
 '54% off',
 '60% off',
 '68% off',
 '75% off',
 '55% off',
 '50% off',
 '63% off',
 '64% off',
 '55% off',
 '10% off',
 '56% off',
 '55% off',
 '68% off',
 '16% off',
 '64% off',
 '62% off',
 '60% off',
 '55% off',
 '20% off',
 '55% off',
 '62% off',
 '47% off',
 '61% off',
 '58% off',
 '55% off',
 '23% off',
 '52% off',
 '40% off',
 '55% off',
 '69% off',
 '60% off',
 '52% off',
 '65% off',
 '85% off',
 '64% off',
 '55% off',
 '55% off',
 '23% off',
 '80% off',
 '28% off',
 '54% off',
 '74% off',
 '80% off',
 '59% off',
 '55% off',
 '69% off',
 '49% off',
 '70% off',
 '55% off',
 '61% off',
 '52% off',
 '71% off',
 '60% off',
 '77% off',
 '65% off',
 '46% off',
 '80% off',
 '56% off',
 '65% off',
 '51% off',
 '68% off']

In [304]:
df=pd.DataFrame()
df['Brand']=brands[0:99]
df['description']=desc[0:99]
df['discount']=disc[0:99]
df

        Brand                                        description discount
0   bluemaker          casual for men (blue 08) Sneakers For Men  55% off
1   bluemaker                                   Sneakers For Men  55% off
2    Magnolia                                   Sneakers For Men  64% off
3      BRUTON  Combo Pack Of 4 Casual Shoes Loafer Shoes Snea...  86% off
4      Chevit  Perfect & Affordable Combo Pack of 02 Pairs Sn...  66% off
..        ...                                                ...      ...
94    LuvShus  Casual , Partywear Sneakers Shoes For Men's An...  55% off
95  BAUCHHAAR                      ADISET 1.0 M Sneakers For Men  55% off
96      SPARX             Lazy Knit Slip On IDP Sneakers For Men  23% off
97  India hub                                   Sneakers For Men  80% off
98      BIRDE                                   Sneakers For Men  28% off

[99 rows x 3 columns]

Q9: Go to the link - https://www.myntra.com/shoes
Set Price filter to “Rs. 6649 to Rs. 13099” , Color filter to “Black”, as shown in 
the below image

In [305]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [306]:
url='https://www.myntra.com/shoes'
driver.get(url)

In [307]:
search_btn=driver.find_elements_by_xpath("//li[@class ='colour-listItem']//label[@class ='common-customCheckbox']/div[@class = 'common-checkboxIndicator']")
search_btn[0].click()

In [308]:
search_btn=driver.find_elements_by_xpath("//ul[@class ='price-list']//label[@class ='common-customCheckbox vertical-filters-label']/div[@class = 'common-checkboxIndicator']")
search_btn[1].click()

In [309]:
page_url=[]
url = driver.find_elements_by_xpath("//li[@class='pagination-number']//a")[:2]
for i in url:
    page_url.append(i.get_attribute('href'))
page_url

['https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6935.0_13621.0_6935.0%20TO%2013621.0&p=2',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6935.0_13621.0_6935.0%20TO%2013621.0&p=3']

In [310]:
product_brands=[]
for i in page_url:
    driver.get(i)
    brand=driver.find_elements_by_xpath("//h3[@class='product-brand']")[:100]
    for i in brand:
        product_brands.append(i.text)
product_brands

['Saint G',
 'ASICS',
 'J.FONTINI',
 'J.FONTINI',
 'Saint G',
 'Heel & Buckle London',
 'Puma',
 'KIPRUN By Decathlon',
 'PUMA Motorsport',
 'Puma',
 'Puma',
 'Heel & Buckle London',
 'Cole Haan',
 'Cole Haan',
 'Cole Haan',
 'VIONIC',
 'J.FONTINI',
 'J.FONTINI',
 'J.FONTINI',
 'Kalenji By Decathlon',
 'Puma',
 'Nike',
 'PUMA Motorsport',
 'Geox',
 'Puma',
 'Heel & Buckle London',
 'ASICS',
 'ASICS',
 'ASICS',
 'Bugatti',
 'Bugatti',
 'Saint G',
 'Heel & Buckle London',
 'Saint G',
 'Saint G',
 'Kenneth Cole',
 'Heel & Buckle London',
 'Geox',
 'J.FONTINI',
 'Geox',
 'Geox',
 'Geox',
 'Cole Haan',
 'Florsheim',
 'Tommy Hilfiger',
 'Heel & Buckle London',
 'Ruosh',
 'Heel & Buckle London',
 'PUMA Motorsport',
 'Puma',
 'Puma',
 'Nike',
 'Nike',
 'J.FONTINI',
 'Nike',
 'J.FONTINI',
 'J.FONTINI',
 'Heel & Buckle London',
 'Kenneth Cole',
 'Kenneth Cole',
 'Nike',
 'J.FONTINI',
 'Saint G',
 'Geox',
 'Geox',
 'Geox',
 'Nike',
 'ASICS',
 'DAVINCHI',
 'Sole To Soul',
 'Sole To Soul',
 'Tommy Hilfiger',
 'Sole To Soul',
 'DAVINCHI',
 'Saint G',
 'Puma',
 'Nike',
 'Geox',
 'Tommy Hilfiger',
 'DAVINCHI',
 'J.FONTINI',
 'J.FONTINI',
 'PUMA Motorsport',
 'DAVINCHI',
 'DAVINCHI',
 'DAVINCHI',
 'Cole Haan',
 'Nike',
 'Nike',
 'UNDER ARMOUR',
 'Clarks',
 'Puma',
 'ADIDAS',
 'Florsheim',
 'Puma',
 'Puma',
 'ADIDAS',
 'Puma',
 'PUMA Motorsport',
 'ASICS']

In [311]:
description=[]
for i in page_url:
    driver.get(i)
    descrip=driver.find_elements_by_xpath("//h4[@class='product-product']")[:100]
    for i in descrip:
        description.append(i.text)
description

['Mercedes F1 Drift Cat Shoes',
 'Leather Block Sandals',
 'Women GlideRide Running Shoes',
 'Men Solid Leather Formal Derbys',
 'Women Leather Heeled Boots',
 'Women Solid Leather Gladiators',
 'Women RS-Curve City Sneakers',
 'Women Running Shoes',
 'Women BMW M Motorsport Shoes',
 'Women Fuse Moto Training Shoes',
 'Women Liberate NITRO Running',
 'Men Leather Sneakers',
 'Men Wingtip Oxford Sneakers',
 'Men GENERATION ZEROGRAND STITCHLITE',
 'Leather Sneakers',
 'Men Textured Sneakers',
 'Men Textured Leather Loafers',
 'Men Solid Leather Loafers',
 'Men Textured Leather Loafers',
 'Men KD500 Running Shoe',
 'Men Running Shoes',
 'Women Air Zoom Running Shoes',
 'Unisex BMW MMS RS-FastSneakers',
 'Men Leather Formal Slip-Ons',
 'Men Jamming 2.0 Running Shoes',
 'Men Tassel Leather Loafer',
 'Men Tennis Shoes',
 'Men Black Running Sports Shoes',
 'Men GEL-GLYDE 3 MX Running',
 'Men Black Walking Shoes',
 'Men Walking Shoes',
 'Women Leather Heeled Boots',
 'Women Solid Leather Heels',
 'Women Leather Heeled Boots',
 'Women Heeled Boots',
 'Women Leather Pumps',
 'Men Leather Formal Slip-Ons',
 'Women Peep Toe Heels',
 'Men Textured Leather Loafers',
 'Men Solid Sneakers',
 'Men Leather Flat Boots',
 'Men Leather Driving Shoes',
 'Women Open Toe Flats',
 'Men Solid Leather Formal Derbys',
 'Men Leather Formal Loafers',
 'Men Suede Sneakers',
 'Men Solid Leather Formal Monks',
 'Women Leather Pumps',
 'Unisex Mercedes F1 Sneakers',
 'Unisex Pacer Future Sneakers',
 'Unisex Mirage Sport Trainers',
 'Men ZOOM SPAN 3 Running Shoes',
 'Men Solid Leather Formal Slip-Ons',
 'Men Vomero 16 Running Shoes',
 'Men Solid Leather Formal Slip-Ons',
 'Men Leather Formal Loafers',
 'Men Solid Leather Formal Penny Loafers',
 'Women LeatherSneakers',
 'Women Solid Flat Boots',
 'Men Leather Formal Loafers',
 'Men Zoom Winflo 8 Shoes',
 'Leather Block Peep Toes',
 'Leather Heeled Boots',
 'Leather Heeled Boots',
 'Leather Heeled Boots',
 'Men AIR MAX INFINITY Sneakers',
 'Men Gel-Pulse13 G-TX Running',
 'Ustraa black',
 'Women Block Heeled Boots',
 'Platform Peep Toes with Buckles',
 'Men Leather Horsebit Loafers',
 'Block Heeled Boots with Laser Cuts',
 'Men Formal Leather Slip-Ons',
 'Women Embellished Sandals',
 'Unisex KING Pro Football Shoes',
 'Men Air Max 90 Sneakers',
 'Women Mid-Top Flat Boots',
 'Women Hybrid Leather Sneakers',
 'Men Textured Formal Leather Loafers',
 'Men Textured Leather Formal Loafers',
 'Men Solid Leather Shoes',
 'Women F1 Ridge Cat Sneakers',
 'Men Textured Formal Leather Loafers',
 'Men Solid Leather Formal Derbys',
 'Men Solid Formal Leather Slip-On Shoes',
 'Women Leather Sneakers',
 'Men Air Max Infinity 2 Shoes',
 'Men Air Max Infinity 2 Sneaker',
 'HOVR Infinite 2 Running Shoes',
 'Men Leather Loafers',
 'Unisex Colourblocked Sneakers',
 'Men Kaptir Super Sneakers',
 'Men Solid Leather Formal Brogues',
 'Unisex Rebound Future Trainers',
 'Unisex OP-1 PWRFrame Trainers',
 'Men X9000L3 Running Shoes',
 'Unisex Black Sneakers',
 'Unisex Mercedes F1 Sneakers',
 'Men Black Running Shoes',
 'Unisex Running Shoes']

In [312]:
price=[]
for i in page_url:
    driver.get(i)
    money=driver.find_elements_by_xpath("//div[@class='product-price']")[:100]
    for i in money:
        price.append(i.text)
price

['Rs. 7999',
 'Rs. 10355Rs. 10900(5% OFF)',
 'Rs. 11199Rs. 13999(20% OFF)',
 'Rs. 6990',
 'Rs. 7600',
 'Rs. 6993Rs. 9990(30% OFF)',
 'Rs. 6999',
 'Rs. 7006Rs. 7149(2% OFF)',
 'Rs. 6999',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7693Rs. 10990(30% OFF)',
 'Rs. 12999',
 'Rs. 11999',
 'Rs. 10999',
 'Rs. 7039Rs. 10999(36% OFF)',
 'Rs. 7990',
 'Rs. 7990',
 'Rs. 7990',
 'Rs. 7773Rs. 8449(8% OFF)',
 'Rs. 10399Rs. 12999(20% OFF)',
 'Rs. 10295',
 'Rs. 7499Rs. 9999(25% OFF)',
 'Rs. 8999',
 'Rs. 12999',
 'Rs. 9093Rs. 12990(30% OFF)',
 'Rs. 9999',
 'Rs. 7999',
 'Rs. 7199Rs. 8999(20% OFF)',
 'Rs. 8999',
 'Rs. 8999',
 'Rs. 8900',
 'Rs. 6993Rs. 9990(30% OFF)',
 'Rs. 8500',
 'Rs. 8000',
 'Rs. 10493Rs. 14990(30% OFF)',
 'Rs. 11242Rs. 14990(25% OFF)',
 'Rs. 7192Rs. 8990(20% OFF)',
 'Rs. 6990',
 'Rs. 10999',
 'Rs. 11999',
 'Rs. 9999',
 'Rs. 11999',
 'Rs. 6995',
 'Rs. 7992Rs. 9990(20% OFF)',
 'Rs. 7599',
 'Rs. 8990',
 'Rs. 7192Rs. 8990(20% OFF)',
 'Rs. 7999',
 'Rs. 6999',
 'Rs. 8999',
 'Rs. 7195',
 'Rs. 7990',
 'Rs. 13495',
 'Rs. 7990',
 'Rs. 6990',
 'Rs. 8792Rs. 10990(20% OFF)',
 'Rs. 7343Rs. 10490(30% OFF)',
 'Rs. 9513Rs. 13590(30% OFF)',
 'Rs. 8295',
 'Rs. 6990',
 'Rs. 9975Rs. 10500(5% OFF)',
 'Rs. 10999',
 'Rs. 12999',
 'Rs. 11999',
 'Rs. 8295',
 'Rs. 7999Rs. 9999(20% OFF)',
 'Rs. 8990',
 'Rs. 7990',
 'Rs. 7690',
 'Rs. 8599',
 'Rs. 7990',
 'Rs. 8990',
 'Rs. 7000',
 'Rs. 7499Rs. 9999(25% OFF)',
 'Rs. 10295',
 'Rs. 10999',
 'Rs. 7999',
 'Rs. 8990',
 'Rs. 8990',
 'Rs. 6990',
 'Rs. 6999',
 'Rs. 8990',
 'Rs. 6990',
 'Rs. 10999',
 'Rs. 8990',
 'Rs. 8295',
 'Rs. 8295',
 'Rs. 11999',
 'Rs. 6999',
 'Rs. 7999',
 'Rs. 8999',
 'Rs. 7495',
 'Rs. 6999',
 'Rs. 10999',
 'Rs. 11999',
 'Rs. 7499',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 9999']

In [313]:
df=pd.DataFrame()
df['Brand']=product_brands
df['description']=description
df['price']=price
df

,Brand,description,price
0,Saint G,Mercedes F1 Drift Cat Shoes,Rs. 7999
1,ASICS,Leather Block Sandals,Rs. 10355Rs. 10900(5% OFF)
2,J.FONTINI,Women GlideRide Running Shoes,Rs. 11199Rs. 13999(20% OFF)
3,J.FONTINI,Men Solid Leather Formal Derbys,Rs. 6990
4,Saint G,Women Leather Heeled Boots,Rs. 7600
...,...,...,...
95,Puma,Men X9000L3 Running Shoes,Rs. 11999
96,ADIDAS,Unisex Black Sneakers,Rs. 7499
97,Puma,Unisex Mercedes F1 Sneakers,Rs. 7999
98,PUMA Motorsport,Men Black Running Shoes,Rs. 9999
99,ASICS,Unisex Running Shoes,Rs. 9999

Q10: Go to webpage https://www.amazon.in/
 Enter “Laptop” in the search field and then click the search icon.

In [314]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
driver=driver = webdriver.Chrome(r'C:\Users\dell\Downloads\chromedriver_win32\chromedriver.exe')
driver

In [315]:
url='https://www.amazon.in/'
driver.get(url)

In [316]:
search=driver.find_element_by_id('twotabsearchtextbox')
search.send_keys('laptops')
btn=driver.find_element_by_id('nav-search-submit-button')
btn.click()

In [317]:
filter=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']/span")

for i in filter:
    if i.text=='Intel Core i7':
        i.click()
        break

In [318]:
filter=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']/span")

for i in filter:
    if i.text=='Intel Core i9':
        i.click()
        break

In [319]:
title=driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']")[:10]

product=[]
for i in title:
    product.append(i.text)
product

['HP Envy 11th Gen Core i7 Processor 13.3-inch (33.78 cms) FHD Touchscreen Laptop (16GB/1TB SSD/Win 10/NVIDIA MX450 2GB/Natural Silver/1.3 kg), 13-ba1018TX',
 'Dell XPS 9370 13.3-inch FHD Display Thin & Light Laptop (8th Gen i7-8550U/16GB/512GB SSD/Win 10 + MS Office/Integrated Graphics), Gold',
 'Mi Notebook Horizon Edition 14 Intel Core i7-10510U 10th Gen Thin and Light Laptop(8GB/512GB SSD/Windows 10/Nvidia MX350 2GB Graphics/Grey/1.35Kg)(Without Webcam) XMA1904-AF',
 'Lenovo IdeaPad S540 11th Gen Intel Core i7 13.3" QHD IPS Thin & Light Laptop (16GB/512GB SSD/Windows 10/MS Office 2019/Intel Iris Xe Graphics/Iron Grey/1.28Kg), 82H1002CIN',
 'ASUS TUF Dash F15 (2021), 15.6-inch (39.62 cms) FHD 144Hz, Intel Core i7-11370H 11th Gen, RTX 3050 4GB Graphics Gaming Laptop (16GB RAM/512GB SSD/Windows 10/White/2 kg), FX516PC-HN062T',
 'HP Pavilion 13(2021) 11th Gen Intel Core i7 Laptop, 16GB RAM, 1TB SSD, 13.3-inch(33.8 cm) FHD Screen, Win 10, MS Office, Ceramic White, 1.24 Kg (13-bb0078TU)',
 'Fujitsu UH-X 11th Gen Intel Core i7 13.3” (33.78cm) FHD IPS 400Nits 2-in1 Touch Convertible Laptop (16GB/1TB SSD/Win10/Office/Iris Xe Graphics/Backlit Kb/Black/997gms), 4ZR1D71993',
 'ASUS TUF Dash F15 (2021) 15.6" (39.62 cm) FHD 240Hz/3ms, Intel Core i7-11370H, GeForce RTX 3060 6GB Graphics, Gaming Laptop (16GB RAM/1TB SSD/Office 2019/Windows 10 Home/Gray/2 Kg) FX516PM-AZ153TS',
 'ASUS ROG G703GI-E5148T 17.3" (43.94 cms) FHD 144Hz/3ms Gaming Laptop (8th Gen Intel Core i9-8950HK/64GB/2TB SSHD + 1.5TB NVMe SSD/Windows 10/GTX 1080 8GB Graphics/4.70 Kg), Aluminum',
 'Fujitsu UH-X 11th Gen Intel i7 Core 13.3” (33.78cm) FHD IPS 400Nits Thin and Light Laptop (16GB/512GB SSD/Win10/Office/Iris Xe Graphics/Backlit Kb/ Fingerprint Reader/Black/878gms), 4ZR1D67596']

In [320]:
rate=driver.find_elements_by_xpath("//span[@class='a-size-base']")[:10]

ratings=[]
for i in rate:
    ratings.append(i.text)
ratings

['231', '11', '815', '101', '4', '29', '13', '31', '29', '66']

In [321]:
money=driver.find_elements_by_xpath("//span[@class='a-price-whole']")[:10]

price=[]
for i in money:
    price.append(i.text)
price

['1,23,350',
 '1,14,990',
 '57,990',
 '77,990',
 '85,990',
 '92,990',
 '1,07,990',
 '1,09,990',
 '5,56,524',
 '92,990']

In [322]:
df=pd.DataFrame({})
df['Title']=product
df['Ratings']=ratings
df['Price']=price
df

                                               Title Ratings     Price
0  HP Envy 11th Gen Core i7 Processor 13.3-inch (...     231  1,23,350
1  Dell XPS 9370 13.3-inch FHD Display Thin & Lig...      11  1,14,990
2  Mi Notebook Horizon Edition 14 Intel Core i7-1...     815    57,990
3  Lenovo IdeaPad S540 11th Gen Intel Core i7 13....     101    77,990
4  ASUS TUF Dash F15 (2021), 15.6-inch (39.62 cms...       4    85,990
5  HP Pavilion 13(2021) 11th Gen Intel Core i7 La...      29    92,990
6  Fujitsu UH-X 11th Gen Intel Core i7 13.3” (33....      13  1,07,990
7  ASUS TUF Dash F15 (2021) 15.6" (39.62 cm) FHD ...      31  1,09,990
8  ASUS ROG G703GI-E5148T 17.3" (43.94 cms) FHD 1...      29  5,56,524
9  Fujitsu UH-X 11th Gen Intel i7 Core 13.3” (33....      66    92,990